/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BaseResponseCommonMapStringLong,
  BaseResponseCommonPageMailReceiverForListDto,
  PageableDto,
  SearchMailReceiverDto,
} from '../models/index';
import {
    BaseResponseCommonMapStringLongFromJSON,
    BaseResponseCommonMapStringLongToJSON,
    BaseResponseCommonPageMailReceiverForListDtoFromJSON,
    BaseResponseCommonPageMailReceiverForListDtoToJSON,
    PageableDtoFromJSON,
    PageableDtoToJSON,
    SearchMailReceiverDtoFromJSON,
    SearchMailReceiverDtoToJSON,
} from '../models/index';

export interface FindMailReceiverListByMailingIdRequest {
    searchDto: SearchMailReceiverDto;
    pageableDto: PageableDto;
}

export interface StasticsMailingByIdRequest {
    searchDto: SearchMailReceiverDto;
}

/**
 * 
 */
export class MailReceiverControllerApi extends runtime.BaseAPI {

    /**
     * 발송 이력 리스트 가져오기
     * 발송 이력 리스트
     */
    async findMailReceiverListByMailingIdRaw(requestParameters: FindMailReceiverListByMailingIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseCommonPageMailReceiverForListDto>> {
        if (requestParameters['searchDto'] == null) {
            throw new runtime.RequiredError(
                'searchDto',
                'Required parameter "searchDto" was null or undefined when calling findMailReceiverListByMailingId().'
            );
        }

        if (requestParameters['pageableDto'] == null) {
            throw new runtime.RequiredError(
                'pageableDto',
                'Required parameter "pageableDto" was null or undefined when calling findMailReceiverListByMailingId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['searchDto'] != null) {
            queryParameters['searchDto'] = requestParameters['searchDto'];
        }

        if (requestParameters['pageableDto'] != null) {
            queryParameters['pageableDto'] = requestParameters['pageableDto'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/svc/mailreceiver`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseCommonPageMailReceiverForListDtoFromJSON(jsonValue));
    }

    /**
     * 발송 이력 리스트 가져오기
     * 발송 이력 리스트
     */
    async findMailReceiverListByMailingId(requestParameters: FindMailReceiverListByMailingIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseCommonPageMailReceiverForListDto> {
        const response = await this.findMailReceiverListByMailingIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 발송 통계 상세 보기
     * 발송 통계 상세 보기
     */
    async stasticsMailingByIdRaw(requestParameters: StasticsMailingByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BaseResponseCommonMapStringLong>> {
        if (requestParameters['searchDto'] == null) {
            throw new runtime.RequiredError(
                'searchDto',
                'Required parameter "searchDto" was null or undefined when calling stasticsMailingById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['searchDto'] != null) {
            queryParameters['searchDto'] = requestParameters['searchDto'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("accessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/svc/mailreceiver/stastics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BaseResponseCommonMapStringLongFromJSON(jsonValue));
    }

    /**
     * 발송 통계 상세 보기
     * 발송 통계 상세 보기
     */
    async stasticsMailingById(requestParameters: StasticsMailingByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BaseResponseCommonMapStringLong> {
        const response = await this.stasticsMailingByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
