version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: mediabee-website
    command: yarn start
    ports:
      - "4191:4191"

#  storybook:
#    image: mediabee-front
#    command: sh -c 'sleep 5 && yarn storybook:start'
#    ports:
#      - "4561:4561"
#    depends_on:
#      - server


