/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeNameCountDto } from './CodeNameCountDto';
import {
    CodeNameCountDtoFromJSON,
    CodeNameCountDtoFromJSONTyped,
    CodeNameCountDtoToJSON,
} from './CodeNameCountDto';

/**
 * 
 * @export
 * @interface ActionFilterDto
 */
export interface ActionFilterDto {
    /**
     * 
     * @type {Array<CodeNameCountDto>}
     * @memberof ActionFilterDto
     */
    codeNameCountListCategory?: Array<CodeNameCountDto>;
    /**
     * 
     * @type {Array<CodeNameCountDto>}
     * @memberof ActionFilterDto
     */
    codeNameCountListState?: Array<CodeNameCountDto>;
    /**
     * 
     * @type {Array<CodeNameCountDto>}
     * @memberof ActionFilterDto
     */
    codeNameCountListOwner?: Array<CodeNameCountDto>;
    /**
     * 
     * @type {Array<CodeNameCountDto>}
     * @memberof ActionFilterDto
     */
    codeNameCountListTag?: Array<CodeNameCountDto>;
    /**
     * 
     * @type {Array<CodeNameCountDto>}
     * @memberof ActionFilterDto
     */
    codeNameCountListMedia?: Array<CodeNameCountDto>;
}

/**
 * Check if a given object implements the ActionFilterDto interface.
 */
export function instanceOfActionFilterDto(value: object): value is ActionFilterDto {
    return true;
}

export function ActionFilterDtoFromJSON(json: any): ActionFilterDto {
    return ActionFilterDtoFromJSONTyped(json, false);
}

export function ActionFilterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionFilterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'codeNameCountListCategory': json['codeNameCountListCategory'] == null ? undefined : ((json['codeNameCountListCategory'] as Array<any>).map(CodeNameCountDtoFromJSON)),
        'codeNameCountListState': json['codeNameCountListState'] == null ? undefined : ((json['codeNameCountListState'] as Array<any>).map(CodeNameCountDtoFromJSON)),
        'codeNameCountListOwner': json['codeNameCountListOwner'] == null ? undefined : ((json['codeNameCountListOwner'] as Array<any>).map(CodeNameCountDtoFromJSON)),
        'codeNameCountListTag': json['codeNameCountListTag'] == null ? undefined : ((json['codeNameCountListTag'] as Array<any>).map(CodeNameCountDtoFromJSON)),
        'codeNameCountListMedia': json['codeNameCountListMedia'] == null ? undefined : ((json['codeNameCountListMedia'] as Array<any>).map(CodeNameCountDtoFromJSON)),
    };
}

export function ActionFilterDtoToJSON(value?: ActionFilterDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'codeNameCountListCategory': value['codeNameCountListCategory'] == null ? undefined : ((value['codeNameCountListCategory'] as Array<any>).map(CodeNameCountDtoToJSON)),
        'codeNameCountListState': value['codeNameCountListState'] == null ? undefined : ((value['codeNameCountListState'] as Array<any>).map(CodeNameCountDtoToJSON)),
        'codeNameCountListOwner': value['codeNameCountListOwner'] == null ? undefined : ((value['codeNameCountListOwner'] as Array<any>).map(CodeNameCountDtoToJSON)),
        'codeNameCountListTag': value['codeNameCountListTag'] == null ? undefined : ((value['codeNameCountListTag'] as Array<any>).map(CodeNameCountDtoToJSON)),
        'codeNameCountListMedia': value['codeNameCountListMedia'] == null ? undefined : ((value['codeNameCountListMedia'] as Array<any>).map(CodeNameCountDtoToJSON)),
    };
}

