/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateInquiryForNoUserDto } from './CreateInquiryForNoUserDto';
import {
    CreateInquiryForNoUserDtoFromJSON,
    CreateInquiryForNoUserDtoFromJSONTyped,
    CreateInquiryForNoUserDtoToJSON,
} from './CreateInquiryForNoUserDto';

/**
 * 
 * @export
 * @interface AddInquiryForNoUserRequest
 */
export interface AddInquiryForNoUserRequest {
    /**
     * 
     * @type {CreateInquiryForNoUserDto}
     * @memberof AddInquiryForNoUserRequest
     */
    request: CreateInquiryForNoUserDto;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof AddInquiryForNoUserRequest
     */
    fileList?: Array<Blob>;
}

/**
 * Check if a given object implements the AddInquiryForNoUserRequest interface.
 */
export function instanceOfAddInquiryForNoUserRequest(value: object): value is AddInquiryForNoUserRequest {
    if (!('request' in value) || value['request'] === undefined) return false;
    return true;
}

export function AddInquiryForNoUserRequestFromJSON(json: any): AddInquiryForNoUserRequest {
    return AddInquiryForNoUserRequestFromJSONTyped(json, false);
}

export function AddInquiryForNoUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddInquiryForNoUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'request': CreateInquiryForNoUserDtoFromJSON(json['request']),
        'fileList': json['fileList'] == null ? undefined : json['fileList'],
    };
}

export function AddInquiryForNoUserRequestToJSON(value?: AddInquiryForNoUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request': CreateInquiryForNoUserDtoToJSON(value['request']),
        'fileList': value['fileList'],
    };
}

