/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFileAttachDto } from './CreateFileAttachDto';
import {
    CreateFileAttachDtoFromJSON,
    CreateFileAttachDtoFromJSONTyped,
    CreateFileAttachDtoToJSON,
} from './CreateFileAttachDto';

/**
 * 
 * @export
 * @interface AddMediaFileRequest
 */
export interface AddMediaFileRequest {
    /**
     * 
     * @type {CreateFileAttachDto}
     * @memberof AddMediaFileRequest
     */
    request: CreateFileAttachDto;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof AddMediaFileRequest
     */
    fileList: Array<Blob>;
}

/**
 * Check if a given object implements the AddMediaFileRequest interface.
 */
export function instanceOfAddMediaFileRequest(value: object): value is AddMediaFileRequest {
    if (!('request' in value) || value['request'] === undefined) return false;
    if (!('fileList' in value) || value['fileList'] === undefined) return false;
    return true;
}

export function AddMediaFileRequestFromJSON(json: any): AddMediaFileRequest {
    return AddMediaFileRequestFromJSONTyped(json, false);
}

export function AddMediaFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMediaFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'request': CreateFileAttachDtoFromJSON(json['request']),
        'fileList': json['fileList'],
    };
}

export function AddMediaFileRequestToJSON(value?: AddMediaFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request': CreateFileAttachDtoToJSON(value['request']),
        'fileList': value['fileList'],
    };
}

