/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateMailingDto } from './CreateMailingDto';
import {
    CreateMailingDtoFromJSON,
    CreateMailingDtoFromJSONTyped,
    CreateMailingDtoToJSON,
} from './CreateMailingDto';

/**
 * 
 * @export
 * @interface AddMailingRequest
 */
export interface AddMailingRequest {
    /**
     * 
     * @type {CreateMailingDto}
     * @memberof AddMailingRequest
     */
    request: CreateMailingDto;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof AddMailingRequest
     */
    fileList?: Array<Blob>;
}

/**
 * Check if a given object implements the AddMailingRequest interface.
 */
export function instanceOfAddMailingRequest(value: object): value is AddMailingRequest {
    if (!('request' in value) || value['request'] === undefined) return false;
    return true;
}

export function AddMailingRequestFromJSON(json: any): AddMailingRequest {
    return AddMailingRequestFromJSONTyped(json, false);
}

export function AddMailingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMailingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'request': CreateMailingDtoFromJSON(json['request']),
        'fileList': json['fileList'] == null ? undefined : json['fileList'],
    };
}

export function AddMailingRequestToJSON(value?: AddMailingRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request': CreateMailingDtoToJSON(value['request']),
        'fileList': value['fileList'],
    };
}

