/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddOneJournalistGroupDto
 */
export interface AddOneJournalistGroupDto {
    /**
     * 언론인목록 ID
     * @type {number}
     * @memberof AddOneJournalistGroupDto
     */
    jrnlstListId: number;
    /**
     * 언론인 ID
     * @type {number}
     * @memberof AddOneJournalistGroupDto
     */
    journalistId: number;
}

/**
 * Check if a given object implements the AddOneJournalistGroupDto interface.
 */
export function instanceOfAddOneJournalistGroupDto(value: object): value is AddOneJournalistGroupDto {
    if (!('jrnlstListId' in value) || value['jrnlstListId'] === undefined) return false;
    if (!('journalistId' in value) || value['journalistId'] === undefined) return false;
    return true;
}

export function AddOneJournalistGroupDtoFromJSON(json: any): AddOneJournalistGroupDto {
    return AddOneJournalistGroupDtoFromJSONTyped(json, false);
}

export function AddOneJournalistGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOneJournalistGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'jrnlstListId': json['jrnlstListId'],
        'journalistId': json['journalistId'],
    };
}

export function AddOneJournalistGroupDtoToJSON(value?: AddOneJournalistGroupDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jrnlstListId': value['jrnlstListId'],
        'journalistId': value['journalistId'],
    };
}

