/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailSendResponse } from './EmailSendResponse';
import {
    EmailSendResponseFromJSON,
    EmailSendResponseFromJSONTyped,
    EmailSendResponseToJSON,
} from './EmailSendResponse';

/**
 * 
 * @export
 * @interface ApiResponseEmailSendResponse
 */
export interface ApiResponseEmailSendResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiResponseEmailSendResponse
     */
    httpStatusCode?: number;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ApiResponseEmailSendResponse
     */
    httpHeaders?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {EmailSendResponse}
     * @memberof ApiResponseEmailSendResponse
     */
    body?: EmailSendResponse;
}

/**
 * Check if a given object implements the ApiResponseEmailSendResponse interface.
 */
export function instanceOfApiResponseEmailSendResponse(value: object): value is ApiResponseEmailSendResponse {
    return true;
}

export function ApiResponseEmailSendResponseFromJSON(json: any): ApiResponseEmailSendResponse {
    return ApiResponseEmailSendResponseFromJSONTyped(json, false);
}

export function ApiResponseEmailSendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiResponseEmailSendResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'httpStatusCode': json['httpStatusCode'] == null ? undefined : json['httpStatusCode'],
        'httpHeaders': json['httpHeaders'] == null ? undefined : json['httpHeaders'],
        'body': json['body'] == null ? undefined : EmailSendResponseFromJSON(json['body']),
    };
}

export function ApiResponseEmailSendResponseToJSON(value?: ApiResponseEmailSendResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'httpStatusCode': value['httpStatusCode'],
        'httpHeaders': value['httpHeaders'],
        'body': EmailSendResponseToJSON(value['body']),
    };
}

