/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { NewsSrchDto } from './NewsSrchDto';
import {
    NewsSrchDtoFromJSON,
    NewsSrchDtoFromJSONTyped,
    NewsSrchDtoToJSON,
} from './NewsSrchDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonNewsSrchDto
 */
export interface BaseResponseCommonNewsSrchDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonNewsSrchDto
     */
    status?: string;
    /**
     * 
     * @type {NewsSrchDto}
     * @memberof BaseResponseCommonNewsSrchDto
     */
    data?: NewsSrchDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonNewsSrchDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonNewsSrchDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonNewsSrchDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonNewsSrchDto interface.
 */
export function instanceOfBaseResponseCommonNewsSrchDto(value: object): value is BaseResponseCommonNewsSrchDto {
    return true;
}

export function BaseResponseCommonNewsSrchDtoFromJSON(json: any): BaseResponseCommonNewsSrchDto {
    return BaseResponseCommonNewsSrchDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonNewsSrchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonNewsSrchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : NewsSrchDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonNewsSrchDtoToJSON(value?: BaseResponseCommonNewsSrchDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': NewsSrchDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

