/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { JournalistSrchDto } from './JournalistSrchDto';
import {
    JournalistSrchDtoFromJSON,
    JournalistSrchDtoFromJSONTyped,
    JournalistSrchDtoToJSON,
} from './JournalistSrchDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonJournalistSrchDto
 */
export interface BaseResponseCommonJournalistSrchDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonJournalistSrchDto
     */
    status?: string;
    /**
     * 
     * @type {JournalistSrchDto}
     * @memberof BaseResponseCommonJournalistSrchDto
     */
    data?: JournalistSrchDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonJournalistSrchDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonJournalistSrchDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonJournalistSrchDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonJournalistSrchDto interface.
 */
export function instanceOfBaseResponseCommonJournalistSrchDto(value: object): value is BaseResponseCommonJournalistSrchDto {
    return true;
}

export function BaseResponseCommonJournalistSrchDtoFromJSON(json: any): BaseResponseCommonJournalistSrchDto {
    return BaseResponseCommonJournalistSrchDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonJournalistSrchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonJournalistSrchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : JournalistSrchDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonJournalistSrchDtoToJSON(value?: BaseResponseCommonJournalistSrchDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': JournalistSrchDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

