/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { CouponNewswireDto } from './CouponNewswireDto';
import {
    CouponNewswireDtoFromJSON,
    CouponNewswireDtoFromJSONTyped,
    CouponNewswireDtoToJSON,
} from './CouponNewswireDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonCouponNewswireDto
 */
export interface BaseResponseCommonCouponNewswireDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonCouponNewswireDto
     */
    status?: string;
    /**
     * 
     * @type {CouponNewswireDto}
     * @memberof BaseResponseCommonCouponNewswireDto
     */
    data?: CouponNewswireDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonCouponNewswireDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonCouponNewswireDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonCouponNewswireDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonCouponNewswireDto interface.
 */
export function instanceOfBaseResponseCommonCouponNewswireDto(value: object): value is BaseResponseCommonCouponNewswireDto {
    return true;
}

export function BaseResponseCommonCouponNewswireDtoFromJSON(json: any): BaseResponseCommonCouponNewswireDto {
    return BaseResponseCommonCouponNewswireDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonCouponNewswireDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonCouponNewswireDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : CouponNewswireDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonCouponNewswireDtoToJSON(value?: BaseResponseCommonCouponNewswireDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': CouponNewswireDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

