/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageNewsSrchDto } from './PageNewsSrchDto';
import {
    PageNewsSrchDtoFromJSON,
    PageNewsSrchDtoFromJSONTyped,
    PageNewsSrchDtoToJSON,
} from './PageNewsSrchDto';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonPageNewsSrchDto
 */
export interface BaseResponseCommonPageNewsSrchDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonPageNewsSrchDto
     */
    status?: string;
    /**
     * 
     * @type {PageNewsSrchDto}
     * @memberof BaseResponseCommonPageNewsSrchDto
     */
    data?: PageNewsSrchDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonPageNewsSrchDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonPageNewsSrchDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonPageNewsSrchDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonPageNewsSrchDto interface.
 */
export function instanceOfBaseResponseCommonPageNewsSrchDto(value: object): value is BaseResponseCommonPageNewsSrchDto {
    return true;
}

export function BaseResponseCommonPageNewsSrchDtoFromJSON(json: any): BaseResponseCommonPageNewsSrchDto {
    return BaseResponseCommonPageNewsSrchDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonPageNewsSrchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonPageNewsSrchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : PageNewsSrchDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonPageNewsSrchDtoToJSON(value?: BaseResponseCommonPageNewsSrchDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': PageNewsSrchDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

