/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { PageMediaListDto } from './PageMediaListDto';
import {
    PageMediaListDtoFromJSON,
    PageMediaListDtoFromJSONTyped,
    PageMediaListDtoToJSON,
} from './PageMediaListDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonPageMediaListDto
 */
export interface BaseResponseCommonPageMediaListDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonPageMediaListDto
     */
    status?: string;
    /**
     * 
     * @type {PageMediaListDto}
     * @memberof BaseResponseCommonPageMediaListDto
     */
    data?: PageMediaListDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonPageMediaListDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonPageMediaListDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonPageMediaListDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonPageMediaListDto interface.
 */
export function instanceOfBaseResponseCommonPageMediaListDto(value: object): value is BaseResponseCommonPageMediaListDto {
    return true;
}

export function BaseResponseCommonPageMediaListDtoFromJSON(json: any): BaseResponseCommonPageMediaListDto {
    return BaseResponseCommonPageMediaListDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonPageMediaListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonPageMediaListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : PageMediaListDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonPageMediaListDtoToJSON(value?: BaseResponseCommonPageMediaListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': PageMediaListDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

