/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaAutoCompleteDto } from './MediaAutoCompleteDto';
import {
    MediaAutoCompleteDtoFromJSON,
    MediaAutoCompleteDtoFromJSONTyped,
    MediaAutoCompleteDtoToJSON,
} from './MediaAutoCompleteDto';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonListMediaAutoCompleteDto
 */
export interface BaseResponseCommonListMediaAutoCompleteDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListMediaAutoCompleteDto
     */
    status?: string;
    /**
     * 
     * @type {Array<MediaAutoCompleteDto>}
     * @memberof BaseResponseCommonListMediaAutoCompleteDto
     */
    data?: Array<MediaAutoCompleteDto>;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListMediaAutoCompleteDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonListMediaAutoCompleteDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListMediaAutoCompleteDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonListMediaAutoCompleteDto interface.
 */
export function instanceOfBaseResponseCommonListMediaAutoCompleteDto(value: object): value is BaseResponseCommonListMediaAutoCompleteDto {
    return true;
}

export function BaseResponseCommonListMediaAutoCompleteDtoFromJSON(json: any): BaseResponseCommonListMediaAutoCompleteDto {
    return BaseResponseCommonListMediaAutoCompleteDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonListMediaAutoCompleteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonListMediaAutoCompleteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MediaAutoCompleteDtoFromJSON)),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonListMediaAutoCompleteDtoToJSON(value?: BaseResponseCommonListMediaAutoCompleteDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MediaAutoCompleteDtoToJSON)),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

