/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { CommonCodeDto } from './CommonCodeDto';
import {
    CommonCodeDtoFromJSON,
    CommonCodeDtoFromJSONTyped,
    CommonCodeDtoToJSON,
} from './CommonCodeDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonListCommonCodeDto
 */
export interface BaseResponseCommonListCommonCodeDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListCommonCodeDto
     */
    status?: string;
    /**
     * 
     * @type {Array<CommonCodeDto>}
     * @memberof BaseResponseCommonListCommonCodeDto
     */
    data?: Array<CommonCodeDto>;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListCommonCodeDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonListCommonCodeDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListCommonCodeDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonListCommonCodeDto interface.
 */
export function instanceOfBaseResponseCommonListCommonCodeDto(value: object): value is BaseResponseCommonListCommonCodeDto {
    return true;
}

export function BaseResponseCommonListCommonCodeDtoFromJSON(json: any): BaseResponseCommonListCommonCodeDto {
    return BaseResponseCommonListCommonCodeDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonListCommonCodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonListCommonCodeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CommonCodeDtoFromJSON)),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonListCommonCodeDtoToJSON(value?: BaseResponseCommonListCommonCodeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CommonCodeDtoToJSON)),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

