/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { PayRequestAfterPayDto } from './PayRequestAfterPayDto';
import {
    PayRequestAfterPayDtoFromJSON,
    PayRequestAfterPayDtoFromJSONTyped,
    PayRequestAfterPayDtoToJSON,
} from './PayRequestAfterPayDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonPayRequestAfterPayDto
 */
export interface BaseResponseCommonPayRequestAfterPayDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonPayRequestAfterPayDto
     */
    status?: string;
    /**
     * 
     * @type {PayRequestAfterPayDto}
     * @memberof BaseResponseCommonPayRequestAfterPayDto
     */
    data?: PayRequestAfterPayDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonPayRequestAfterPayDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonPayRequestAfterPayDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonPayRequestAfterPayDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonPayRequestAfterPayDto interface.
 */
export function instanceOfBaseResponseCommonPayRequestAfterPayDto(value: object): value is BaseResponseCommonPayRequestAfterPayDto {
    return true;
}

export function BaseResponseCommonPayRequestAfterPayDtoFromJSON(json: any): BaseResponseCommonPayRequestAfterPayDto {
    return BaseResponseCommonPayRequestAfterPayDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonPayRequestAfterPayDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonPayRequestAfterPayDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : PayRequestAfterPayDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonPayRequestAfterPayDtoToJSON(value?: BaseResponseCommonPayRequestAfterPayDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': PayRequestAfterPayDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

