/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { ResponseMailingStatusDto } from './ResponseMailingStatusDto';
import {
    ResponseMailingStatusDtoFromJSON,
    ResponseMailingStatusDtoFromJSONTyped,
    ResponseMailingStatusDtoToJSON,
} from './ResponseMailingStatusDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonResponseMailingStatusDto
 */
export interface BaseResponseCommonResponseMailingStatusDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonResponseMailingStatusDto
     */
    status?: string;
    /**
     * 
     * @type {ResponseMailingStatusDto}
     * @memberof BaseResponseCommonResponseMailingStatusDto
     */
    data?: ResponseMailingStatusDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonResponseMailingStatusDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonResponseMailingStatusDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonResponseMailingStatusDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonResponseMailingStatusDto interface.
 */
export function instanceOfBaseResponseCommonResponseMailingStatusDto(value: object): value is BaseResponseCommonResponseMailingStatusDto {
    return true;
}

export function BaseResponseCommonResponseMailingStatusDtoFromJSON(json: any): BaseResponseCommonResponseMailingStatusDto {
    return BaseResponseCommonResponseMailingStatusDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonResponseMailingStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonResponseMailingStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ResponseMailingStatusDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonResponseMailingStatusDtoToJSON(value?: BaseResponseCommonResponseMailingStatusDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': ResponseMailingStatusDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

