/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { ProductForSimpleDto } from './ProductForSimpleDto';
import {
    ProductForSimpleDtoFromJSON,
    ProductForSimpleDtoFromJSONTyped,
    ProductForSimpleDtoToJSON,
} from './ProductForSimpleDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonListProductForSimpleDto
 */
export interface BaseResponseCommonListProductForSimpleDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListProductForSimpleDto
     */
    status?: string;
    /**
     * 
     * @type {Array<ProductForSimpleDto>}
     * @memberof BaseResponseCommonListProductForSimpleDto
     */
    data?: Array<ProductForSimpleDto>;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListProductForSimpleDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonListProductForSimpleDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListProductForSimpleDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonListProductForSimpleDto interface.
 */
export function instanceOfBaseResponseCommonListProductForSimpleDto(value: object): value is BaseResponseCommonListProductForSimpleDto {
    return true;
}

export function BaseResponseCommonListProductForSimpleDtoFromJSON(json: any): BaseResponseCommonListProductForSimpleDto {
    return BaseResponseCommonListProductForSimpleDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonListProductForSimpleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonListProductForSimpleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ProductForSimpleDtoFromJSON)),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonListProductForSimpleDtoToJSON(value?: BaseResponseCommonListProductForSimpleDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ProductForSimpleDtoToJSON)),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

