/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { ProductCountPriceDto } from './ProductCountPriceDto';
import {
    ProductCountPriceDtoFromJSON,
    ProductCountPriceDtoFromJSONTyped,
    ProductCountPriceDtoToJSON,
} from './ProductCountPriceDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonListProductCountPriceDto
 */
export interface BaseResponseCommonListProductCountPriceDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListProductCountPriceDto
     */
    status?: string;
    /**
     * 
     * @type {Array<ProductCountPriceDto>}
     * @memberof BaseResponseCommonListProductCountPriceDto
     */
    data?: Array<ProductCountPriceDto>;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListProductCountPriceDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonListProductCountPriceDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListProductCountPriceDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonListProductCountPriceDto interface.
 */
export function instanceOfBaseResponseCommonListProductCountPriceDto(value: object): value is BaseResponseCommonListProductCountPriceDto {
    return true;
}

export function BaseResponseCommonListProductCountPriceDtoFromJSON(json: any): BaseResponseCommonListProductCountPriceDto {
    return BaseResponseCommonListProductCountPriceDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonListProductCountPriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonListProductCountPriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ProductCountPriceDtoFromJSON)),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonListProductCountPriceDtoToJSON(value?: BaseResponseCommonListProductCountPriceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ProductCountPriceDtoToJSON)),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

