/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { ClipBookDto } from './ClipBookDto';
import {
    ClipBookDtoFromJSON,
    ClipBookDtoFromJSONTyped,
    ClipBookDtoToJSON,
} from './ClipBookDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonClipBookDto
 */
export interface BaseResponseCommonClipBookDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonClipBookDto
     */
    status?: string;
    /**
     * 
     * @type {ClipBookDto}
     * @memberof BaseResponseCommonClipBookDto
     */
    data?: ClipBookDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonClipBookDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonClipBookDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonClipBookDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonClipBookDto interface.
 */
export function instanceOfBaseResponseCommonClipBookDto(value: object): value is BaseResponseCommonClipBookDto {
    return true;
}

export function BaseResponseCommonClipBookDtoFromJSON(json: any): BaseResponseCommonClipBookDto {
    return BaseResponseCommonClipBookDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonClipBookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonClipBookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ClipBookDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonClipBookDtoToJSON(value?: BaseResponseCommonClipBookDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': ClipBookDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

