/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { GroupSimpleDto } from './GroupSimpleDto';
import {
    GroupSimpleDtoFromJSON,
    GroupSimpleDtoFromJSONTyped,
    GroupSimpleDtoToJSON,
} from './GroupSimpleDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonListGroupSimpleDto
 */
export interface BaseResponseCommonListGroupSimpleDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListGroupSimpleDto
     */
    status?: string;
    /**
     * 
     * @type {Array<GroupSimpleDto>}
     * @memberof BaseResponseCommonListGroupSimpleDto
     */
    data?: Array<GroupSimpleDto>;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListGroupSimpleDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonListGroupSimpleDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListGroupSimpleDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonListGroupSimpleDto interface.
 */
export function instanceOfBaseResponseCommonListGroupSimpleDto(value: object): value is BaseResponseCommonListGroupSimpleDto {
    return true;
}

export function BaseResponseCommonListGroupSimpleDtoFromJSON(json: any): BaseResponseCommonListGroupSimpleDto {
    return BaseResponseCommonListGroupSimpleDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonListGroupSimpleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonListGroupSimpleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GroupSimpleDtoFromJSON)),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonListGroupSimpleDtoToJSON(value?: BaseResponseCommonListGroupSimpleDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GroupSimpleDtoToJSON)),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

