/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { ElasticSearchReturnDtoNewsDocumentDto } from './ElasticSearchReturnDtoNewsDocumentDto';
import {
    ElasticSearchReturnDtoNewsDocumentDtoFromJSON,
    ElasticSearchReturnDtoNewsDocumentDtoFromJSONTyped,
    ElasticSearchReturnDtoNewsDocumentDtoToJSON,
} from './ElasticSearchReturnDtoNewsDocumentDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto
 */
export interface BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto
     */
    status?: string;
    /**
     * 
     * @type {ElasticSearchReturnDtoNewsDocumentDto}
     * @memberof BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto
     */
    data?: ElasticSearchReturnDtoNewsDocumentDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto interface.
 */
export function instanceOfBaseResponseCommonElasticSearchReturnDtoNewsDocumentDto(value: object): value is BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto {
    return true;
}

export function BaseResponseCommonElasticSearchReturnDtoNewsDocumentDtoFromJSON(json: any): BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto {
    return BaseResponseCommonElasticSearchReturnDtoNewsDocumentDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonElasticSearchReturnDtoNewsDocumentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ElasticSearchReturnDtoNewsDocumentDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonElasticSearchReturnDtoNewsDocumentDtoToJSON(value?: BaseResponseCommonElasticSearchReturnDtoNewsDocumentDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': ElasticSearchReturnDtoNewsDocumentDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

