/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { ResponseSearchCountDto } from './ResponseSearchCountDto';
import {
    ResponseSearchCountDtoFromJSON,
    ResponseSearchCountDtoFromJSONTyped,
    ResponseSearchCountDtoToJSON,
} from './ResponseSearchCountDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonResponseSearchCountDto
 */
export interface BaseResponseCommonResponseSearchCountDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonResponseSearchCountDto
     */
    status?: string;
    /**
     * 
     * @type {ResponseSearchCountDto}
     * @memberof BaseResponseCommonResponseSearchCountDto
     */
    data?: ResponseSearchCountDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonResponseSearchCountDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonResponseSearchCountDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonResponseSearchCountDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonResponseSearchCountDto interface.
 */
export function instanceOfBaseResponseCommonResponseSearchCountDto(value: object): value is BaseResponseCommonResponseSearchCountDto {
    return true;
}

export function BaseResponseCommonResponseSearchCountDtoFromJSON(json: any): BaseResponseCommonResponseSearchCountDto {
    return BaseResponseCommonResponseSearchCountDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonResponseSearchCountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonResponseSearchCountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ResponseSearchCountDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonResponseSearchCountDtoToJSON(value?: BaseResponseCommonResponseSearchCountDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': ResponseSearchCountDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

