/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ElasticSearchReturnFilterDto } from './ElasticSearchReturnFilterDto';
import {
    ElasticSearchReturnFilterDtoFromJSON,
    ElasticSearchReturnFilterDtoFromJSONTyped,
    ElasticSearchReturnFilterDtoToJSON,
} from './ElasticSearchReturnFilterDto';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonElasticSearchReturnFilterDto
 */
export interface BaseResponseCommonElasticSearchReturnFilterDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonElasticSearchReturnFilterDto
     */
    status?: string;
    /**
     * 
     * @type {ElasticSearchReturnFilterDto}
     * @memberof BaseResponseCommonElasticSearchReturnFilterDto
     */
    data?: ElasticSearchReturnFilterDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonElasticSearchReturnFilterDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonElasticSearchReturnFilterDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonElasticSearchReturnFilterDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonElasticSearchReturnFilterDto interface.
 */
export function instanceOfBaseResponseCommonElasticSearchReturnFilterDto(value: object): value is BaseResponseCommonElasticSearchReturnFilterDto {
    return true;
}

export function BaseResponseCommonElasticSearchReturnFilterDtoFromJSON(json: any): BaseResponseCommonElasticSearchReturnFilterDto {
    return BaseResponseCommonElasticSearchReturnFilterDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonElasticSearchReturnFilterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonElasticSearchReturnFilterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ElasticSearchReturnFilterDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonElasticSearchReturnFilterDtoToJSON(value?: BaseResponseCommonElasticSearchReturnFilterDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': ElasticSearchReturnFilterDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

