/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NameCountDto } from './NameCountDto';
import {
    NameCountDtoFromJSON,
    NameCountDtoFromJSONTyped,
    NameCountDtoToJSON,
} from './NameCountDto';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonListNameCountDto
 */
export interface BaseResponseCommonListNameCountDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListNameCountDto
     */
    status?: string;
    /**
     * 
     * @type {Array<NameCountDto>}
     * @memberof BaseResponseCommonListNameCountDto
     */
    data?: Array<NameCountDto>;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListNameCountDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonListNameCountDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonListNameCountDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonListNameCountDto interface.
 */
export function instanceOfBaseResponseCommonListNameCountDto(value: object): value is BaseResponseCommonListNameCountDto {
    return true;
}

export function BaseResponseCommonListNameCountDtoFromJSON(json: any): BaseResponseCommonListNameCountDto {
    return BaseResponseCommonListNameCountDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonListNameCountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonListNameCountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(NameCountDtoFromJSON)),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonListNameCountDtoToJSON(value?: BaseResponseCommonListNameCountDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(NameCountDtoToJSON)),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

