/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { ActionFilterDto } from './ActionFilterDto';
import {
    ActionFilterDtoFromJSON,
    ActionFilterDtoFromJSONTyped,
    ActionFilterDtoToJSON,
} from './ActionFilterDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonActionFilterDto
 */
export interface BaseResponseCommonActionFilterDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonActionFilterDto
     */
    status?: string;
    /**
     * 
     * @type {ActionFilterDto}
     * @memberof BaseResponseCommonActionFilterDto
     */
    data?: ActionFilterDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonActionFilterDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonActionFilterDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonActionFilterDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonActionFilterDto interface.
 */
export function instanceOfBaseResponseCommonActionFilterDto(value: object): value is BaseResponseCommonActionFilterDto {
    return true;
}

export function BaseResponseCommonActionFilterDtoFromJSON(json: any): BaseResponseCommonActionFilterDto {
    return BaseResponseCommonActionFilterDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonActionFilterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonActionFilterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : ActionFilterDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonActionFilterDtoToJSON(value?: BaseResponseCommonActionFilterDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': ActionFilterDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

