/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDto } from './MessageDto';
import {
    MessageDtoFromJSON,
    MessageDtoFromJSONTyped,
    MessageDtoToJSON,
} from './MessageDto';
import type { JournalistDto } from './JournalistDto';
import {
    JournalistDtoFromJSON,
    JournalistDtoFromJSONTyped,
    JournalistDtoToJSON,
} from './JournalistDto';

/**
 * 
 * @export
 * @interface BaseResponseCommonJournalistDto
 */
export interface BaseResponseCommonJournalistDto {
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonJournalistDto
     */
    status?: string;
    /**
     * 
     * @type {JournalistDto}
     * @memberof BaseResponseCommonJournalistDto
     */
    data?: JournalistDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonJournalistDto
     */
    code?: string;
    /**
     * 
     * @type {MessageDto}
     * @memberof BaseResponseCommonJournalistDto
     */
    message?: MessageDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCommonJournalistDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the BaseResponseCommonJournalistDto interface.
 */
export function instanceOfBaseResponseCommonJournalistDto(value: object): value is BaseResponseCommonJournalistDto {
    return true;
}

export function BaseResponseCommonJournalistDtoFromJSON(json: any): BaseResponseCommonJournalistDto {
    return BaseResponseCommonJournalistDtoFromJSONTyped(json, false);
}

export function BaseResponseCommonJournalistDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCommonJournalistDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : JournalistDtoFromJSON(json['data']),
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : MessageDtoFromJSON(json['message']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function BaseResponseCommonJournalistDtoToJSON(value?: BaseResponseCommonJournalistDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': JournalistDtoToJSON(value['data']),
        'code': value['code'],
        'message': MessageDtoToJSON(value['message']),
        'timestamp': value['timestamp'],
    };
}

