/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 비밀번호 변경
 * @export
 * @interface ChangeContactInfoDto
 */
export interface ChangeContactInfoDto {
    /**
     * 연락처 정보
     * @type {string}
     * @memberof ChangeContactInfoDto
     */
    contactInfo: string;
}

/**
 * Check if a given object implements the ChangeContactInfoDto interface.
 */
export function instanceOfChangeContactInfoDto(value: object): value is ChangeContactInfoDto {
    if (!('contactInfo' in value) || value['contactInfo'] === undefined) return false;
    return true;
}

export function ChangeContactInfoDtoFromJSON(json: any): ChangeContactInfoDto {
    return ChangeContactInfoDtoFromJSONTyped(json, false);
}

export function ChangeContactInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeContactInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'contactInfo': json['contactInfo'],
    };
}

export function ChangeContactInfoDtoToJSON(value?: ChangeContactInfoDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'contactInfo': value['contactInfo'],
    };
}

