/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGroupDto
 */
export interface CreateGroupDto {
    /**
     * 그룹명
     * @type {string}
     * @memberof CreateGroupDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateGroupDto
     */
    isDefault?: boolean;
}

/**
 * Check if a given object implements the CreateGroupDto interface.
 */
export function instanceOfCreateGroupDto(value: object): value is CreateGroupDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateGroupDtoFromJSON(json: any): CreateGroupDto {
    return CreateGroupDtoFromJSONTyped(json, false);
}

export function CreateGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
    };
}

export function CreateGroupDtoToJSON(value?: CreateGroupDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'isDefault': value['isDefault'],
    };
}

