/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateMediaDto } from './CreateMediaDto';
import {
    CreateMediaDtoFromJSON,
    CreateMediaDtoFromJSONTyped,
    CreateMediaDtoToJSON,
} from './CreateMediaDto';

/**
 * 
 * @export
 * @interface CreateMediaArrayDto
 */
export interface CreateMediaArrayDto {
    /**
     * 추가할 미디어 목록
     * @type {Array<CreateMediaDto>}
     * @memberof CreateMediaArrayDto
     */
    createMediaDtoList?: Array<CreateMediaDto>;
}

/**
 * Check if a given object implements the CreateMediaArrayDto interface.
 */
export function instanceOfCreateMediaArrayDto(value: object): value is CreateMediaArrayDto {
    return true;
}

export function CreateMediaArrayDtoFromJSON(json: any): CreateMediaArrayDto {
    return CreateMediaArrayDtoFromJSONTyped(json, false);
}

export function CreateMediaArrayDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMediaArrayDto {
    if (json == null) {
        return json;
    }
    return {
        
        'createMediaDtoList': json['createMediaDtoList'] == null ? undefined : ((json['createMediaDtoList'] as Array<any>).map(CreateMediaDtoFromJSON)),
    };
}

export function CreateMediaArrayDtoToJSON(value?: CreateMediaArrayDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createMediaDtoList': value['createMediaDtoList'] == null ? undefined : ((value['createMediaDtoList'] as Array<any>).map(CreateMediaDtoToJSON)),
    };
}

