/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateJournalistDto } from './CreateJournalistDto';
import {
    CreateJournalistDtoFromJSON,
    CreateJournalistDtoFromJSONTyped,
    CreateJournalistDtoToJSON,
} from './CreateJournalistDto';

/**
 * 
 * @export
 * @interface CreateJournalistArrayDto
 */
export interface CreateJournalistArrayDto {
    /**
     * 추가할 언론인 목록
     * @type {Array<CreateJournalistDto>}
     * @memberof CreateJournalistArrayDto
     */
    createJournalistDtoList?: Array<CreateJournalistDto>;
}

/**
 * Check if a given object implements the CreateJournalistArrayDto interface.
 */
export function instanceOfCreateJournalistArrayDto(value: object): value is CreateJournalistArrayDto {
    return true;
}

export function CreateJournalistArrayDtoFromJSON(json: any): CreateJournalistArrayDto {
    return CreateJournalistArrayDtoFromJSONTyped(json, false);
}

export function CreateJournalistArrayDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJournalistArrayDto {
    if (json == null) {
        return json;
    }
    return {
        
        'createJournalistDtoList': json['createJournalistDtoList'] == null ? undefined : ((json['createJournalistDtoList'] as Array<any>).map(CreateJournalistDtoFromJSON)),
    };
}

export function CreateJournalistArrayDtoToJSON(value?: CreateJournalistArrayDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createJournalistDtoList': value['createJournalistDtoList'] == null ? undefined : ((value['createJournalistDtoList'] as Array<any>).map(CreateJournalistDtoToJSON)),
    };
}

