/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNewswireReleaseDto
 */
export interface CreateNewswireReleaseDto {
    /**
     * 그룹ID
     * @type {number}
     * @memberof CreateNewswireReleaseDto
     */
    groupId: number;
    /**
     * 공유설정
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    shareCode?: string;
    /**
     * 제목
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    title: string;
    /**
     * 부제목
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    subtitle?: string;
    /**
     * 내용
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    content?: string;
    /**
     * 언론 연락처
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    contactPoint: string;
    /**
     * 유튜브 URL
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    youtube?: string;
    /**
     * 유튜브 동영상 설명
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    youtubeComment?: string;
    /**
     * 내 회사와 발표회사가 동일한가?
     * @type {boolean}
     * @memberof CreateNewswireReleaseDto
     */
    isMycomPublisher?: boolean;
    /**
     * 발표 회사 태그 ID
     * @type {number}
     * @memberof CreateNewswireReleaseDto
     */
    publishCompanyId?: number;
    /**
     * 발표 회사명
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    publisher?: string;
    /**
     * 뉴스 발표지
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    publishWhere: string;
    /**
     * 발표회사 웹사이트
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    wsite?: string;
    /**
     * 언어, 공통코드 NEWSWIRE_RELEASE_LANGUAGE
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    language?: string;
    /**
     * 즉시발송 여부
     * @type {boolean}
     * @memberof CreateNewswireReleaseDto
     */
    publishNow?: boolean;
    /**
     * 예약시간 연
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    year: string;
    /**
     * 월
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    month: string;
    /**
     * 일
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    day: string;
    /**
     * 시
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    hour: string;
    /**
     * 분
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    min: string;
    /**
     * 사용자 시간대, 공통코드 - TIMEZONE 
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    timezone: string;
    /**
     * 개제 알림 휴대번호
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    alarmMobile?: string;
    /**
     * 개제 알림 메일
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    alarmEmail?: string;
    /**
     * 요청사항
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    msgToNwire?: string;
    /**
     * 동의한 약관 ID - 뉴스와이어 이용약관
     * @type {number}
     * @memberof CreateNewswireReleaseDto
     */
    termsApproved?: number;
    /**
     * 동의한 약관2 ID - 뉴스와이어 개인정보 취급방침
     * @type {number}
     * @memberof CreateNewswireReleaseDto
     */
    termsApproved2?: number;
    /**
     * 국가 코드
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    countryCode?: string;
    /**
     * 우편번호
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    zipCode?: string;
    /**
     * 주소
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    address?: string;
    /**
     * 상세주소
     * @type {string}
     * @memberof CreateNewswireReleaseDto
     */
    addressDetail?: string;
    /**
     * 관련 태그ID 배열
     * @type {Array<number>}
     * @memberof CreateNewswireReleaseDto
     */
    tagIdList?: Array<number>;
    /**
     * 관련 미디어자료실 파일ID 배열
     * @type {Array<number>}
     * @memberof CreateNewswireReleaseDto
     */
    mediaFileIdList?: Array<number>;
    /**
     * 관련 미디어자료실 파일에 대한 설명, 미디어자료실 파일 순서에 맞도록 보내야함
     * @type {Array<string>}
     * @memberof CreateNewswireReleaseDto
     */
    mediaFileCommentList?: Array<string>;
    /**
     * 로컬 환경에서 직접 올린 이미지 설명, 파일(이미지) 순서에 맞도록 보내야함
     * @type {Array<string>}
     * @memberof CreateNewswireReleaseDto
     */
    fileCommentList?: Array<string>;
}

/**
 * Check if a given object implements the CreateNewswireReleaseDto interface.
 */
export function instanceOfCreateNewswireReleaseDto(value: object): value is CreateNewswireReleaseDto {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('contactPoint' in value) || value['contactPoint'] === undefined) return false;
    if (!('publishWhere' in value) || value['publishWhere'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('day' in value) || value['day'] === undefined) return false;
    if (!('hour' in value) || value['hour'] === undefined) return false;
    if (!('min' in value) || value['min'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    return true;
}

export function CreateNewswireReleaseDtoFromJSON(json: any): CreateNewswireReleaseDto {
    return CreateNewswireReleaseDtoFromJSONTyped(json, false);
}

export function CreateNewswireReleaseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNewswireReleaseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'shareCode': json['shareCode'] == null ? undefined : json['shareCode'],
        'title': json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'content': json['content'] == null ? undefined : json['content'],
        'contactPoint': json['contactPoint'],
        'youtube': json['youtube'] == null ? undefined : json['youtube'],
        'youtubeComment': json['youtubeComment'] == null ? undefined : json['youtubeComment'],
        'isMycomPublisher': json['isMycomPublisher'] == null ? undefined : json['isMycomPublisher'],
        'publishCompanyId': json['publishCompanyId'] == null ? undefined : json['publishCompanyId'],
        'publisher': json['publisher'] == null ? undefined : json['publisher'],
        'publishWhere': json['publishWhere'],
        'wsite': json['wsite'] == null ? undefined : json['wsite'],
        'language': json['language'] == null ? undefined : json['language'],
        'publishNow': json['publishNow'] == null ? undefined : json['publishNow'],
        'year': json['year'],
        'month': json['month'],
        'day': json['day'],
        'hour': json['hour'],
        'min': json['min'],
        'timezone': json['timezone'],
        'alarmMobile': json['alarmMobile'] == null ? undefined : json['alarmMobile'],
        'alarmEmail': json['alarmEmail'] == null ? undefined : json['alarmEmail'],
        'msgToNwire': json['msgToNwire'] == null ? undefined : json['msgToNwire'],
        'termsApproved': json['termsApproved'] == null ? undefined : json['termsApproved'],
        'termsApproved2': json['termsApproved2'] == null ? undefined : json['termsApproved2'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'zipCode': json['zipCode'] == null ? undefined : json['zipCode'],
        'address': json['address'] == null ? undefined : json['address'],
        'addressDetail': json['addressDetail'] == null ? undefined : json['addressDetail'],
        'tagIdList': json['tagIdList'] == null ? undefined : json['tagIdList'],
        'mediaFileIdList': json['mediaFileIdList'] == null ? undefined : json['mediaFileIdList'],
        'mediaFileCommentList': json['mediaFileCommentList'] == null ? undefined : json['mediaFileCommentList'],
        'fileCommentList': json['fileCommentList'] == null ? undefined : json['fileCommentList'],
    };
}

export function CreateNewswireReleaseDtoToJSON(value?: CreateNewswireReleaseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupId': value['groupId'],
        'shareCode': value['shareCode'],
        'title': value['title'],
        'subtitle': value['subtitle'],
        'content': value['content'],
        'contactPoint': value['contactPoint'],
        'youtube': value['youtube'],
        'youtubeComment': value['youtubeComment'],
        'isMycomPublisher': value['isMycomPublisher'],
        'publishCompanyId': value['publishCompanyId'],
        'publisher': value['publisher'],
        'publishWhere': value['publishWhere'],
        'wsite': value['wsite'],
        'language': value['language'],
        'publishNow': value['publishNow'],
        'year': value['year'],
        'month': value['month'],
        'day': value['day'],
        'hour': value['hour'],
        'min': value['min'],
        'timezone': value['timezone'],
        'alarmMobile': value['alarmMobile'],
        'alarmEmail': value['alarmEmail'],
        'msgToNwire': value['msgToNwire'],
        'termsApproved': value['termsApproved'],
        'termsApproved2': value['termsApproved2'],
        'countryCode': value['countryCode'],
        'zipCode': value['zipCode'],
        'address': value['address'],
        'addressDetail': value['addressDetail'],
        'tagIdList': value['tagIdList'],
        'mediaFileIdList': value['mediaFileIdList'],
        'mediaFileCommentList': value['mediaFileCommentList'],
        'fileCommentList': value['fileCommentList'],
    };
}

