/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApplySheetDemoForNoUserDto
 */
export interface CreateApplySheetDemoForNoUserDto {
    /**
     * 이름* 
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    name: string;
    /**
     * 이메일* 
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    email: string;
    /**
     * 전화* 
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    phone?: string;
    /**
     * 휴대전화 
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    mobile?: string;
    /**
     * 부서* 
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    department?: string;
    /**
     * 직책* 
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    position?: string;
    /**
     * 회사명* 
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    comName?: string;
    /**
     * 회사분류* : 공통코드 COM_CATEGORY
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    comCategoryCode?: string;
    /**
     * 사원수* : 공통코드 COM_TOTAL_MEMBERS
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    comTotalMbrsCode?: string;
    /**
     * 웹사이트 
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    comWsite?: string;
    /**
     * ipaddress 
     * @type {string}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    ipAddress?: string;
    /**
     * 약관ID 
     * @type {number}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    clauseId?: number;
    /**
     * 개인정보 수집 및 이용에 동의 
     * @type {boolean}
     * @memberof CreateApplySheetDemoForNoUserDto
     */
    infoGatherAgreed?: boolean;
}

/**
 * Check if a given object implements the CreateApplySheetDemoForNoUserDto interface.
 */
export function instanceOfCreateApplySheetDemoForNoUserDto(value: object): value is CreateApplySheetDemoForNoUserDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateApplySheetDemoForNoUserDtoFromJSON(json: any): CreateApplySheetDemoForNoUserDto {
    return CreateApplySheetDemoForNoUserDtoFromJSONTyped(json, false);
}

export function CreateApplySheetDemoForNoUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApplySheetDemoForNoUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'mobile': json['mobile'] == null ? undefined : json['mobile'],
        'department': json['department'] == null ? undefined : json['department'],
        'position': json['position'] == null ? undefined : json['position'],
        'comName': json['comName'] == null ? undefined : json['comName'],
        'comCategoryCode': json['comCategoryCode'] == null ? undefined : json['comCategoryCode'],
        'comTotalMbrsCode': json['comTotalMbrsCode'] == null ? undefined : json['comTotalMbrsCode'],
        'comWsite': json['comWsite'] == null ? undefined : json['comWsite'],
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'clauseId': json['clauseId'] == null ? undefined : json['clauseId'],
        'infoGatherAgreed': json['infoGatherAgreed'] == null ? undefined : json['infoGatherAgreed'],
    };
}

export function CreateApplySheetDemoForNoUserDtoToJSON(value?: CreateApplySheetDemoForNoUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'mobile': value['mobile'],
        'department': value['department'],
        'position': value['position'],
        'comName': value['comName'],
        'comCategoryCode': value['comCategoryCode'],
        'comTotalMbrsCode': value['comTotalMbrsCode'],
        'comWsite': value['comWsite'],
        'ipAddress': value['ipAddress'],
        'clauseId': value['clauseId'],
        'infoGatherAgreed': value['infoGatherAgreed'],
    };
}

