/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ESearchSentiment
 */
export interface ESearchSentiment {
    /**
     * 
     * @type {number}
     * @memberof ESearchSentiment
     */
    title?: number;
    /**
     * 
     * @type {number}
     * @memberof ESearchSentiment
     */
    body?: number;
    /**
     * 
     * @type {number}
     * @memberof ESearchSentiment
     */
    title_body?: number;
    /**
     * 
     * @type {number}
     * @memberof ESearchSentiment
     */
    body_word_cnt?: number;
}

/**
 * Check if a given object implements the ESearchSentiment interface.
 */
export function instanceOfESearchSentiment(value: object): value is ESearchSentiment {
    return true;
}

export function ESearchSentimentFromJSON(json: any): ESearchSentiment {
    return ESearchSentimentFromJSONTyped(json, false);
}

export function ESearchSentimentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ESearchSentiment {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'body': json['body'] == null ? undefined : json['body'],
        'title_body': json['title_body'] == null ? undefined : json['title_body'],
        'body_word_cnt': json['body_word_cnt'] == null ? undefined : json['body_word_cnt'],
    };
}

export function ESearchSentimentToJSON(value?: ESearchSentiment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'body': value['body'],
        'title_body': value['title_body'],
        'body_word_cnt': value['body_word_cnt'],
    };
}

