/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 관련 언론인 ID/Name 목록, ID 없는 경우 매핑 안된 언론인 
 * @export
 * @interface IdNameDto
 */
export interface IdNameDto {
    /**
     * 
     * @type {string}
     * @memberof IdNameDto
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof IdNameDto
     */
    id?: number;
}

/**
 * Check if a given object implements the IdNameDto interface.
 */
export function instanceOfIdNameDto(value: object): value is IdNameDto {
    return true;
}

export function IdNameDtoFromJSON(json: any): IdNameDto {
    return IdNameDtoFromJSONTyped(json, false);
}

export function IdNameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdNameDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function IdNameDtoToJSON(value?: IdNameDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'id': value['id'],
    };
}

