/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 전담 작업자 정보
 * @export
 * @interface MemberDto
 */
export interface MemberDto {
    /**
     * 
     * @type {number}
     * @memberof MemberDto
     */
    memberId?: number;
    /**
     * 
     * @type {string}
     * @memberof MemberDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberDto
     */
    position?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberDto
     */
    departmentName?: string;
}

/**
 * Check if a given object implements the MemberDto interface.
 */
export function instanceOfMemberDto(value: object): value is MemberDto {
    return true;
}

export function MemberDtoFromJSON(json: any): MemberDto {
    return MemberDtoFromJSONTyped(json, false);
}

export function MemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'position': json['position'] == null ? undefined : json['position'],
        'departmentName': json['departmentName'] == null ? undefined : json['departmentName'],
    };
}

export function MemberDtoToJSON(value?: MemberDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memberId': value['memberId'],
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'position': value['position'],
        'departmentName': value['departmentName'],
    };
}

