/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 회원 대시보드 정보
 * @export
 * @interface ModifyDashboardDto
 */
export interface ModifyDashboardDto {
    /**
     * 대시보드 layout
     * @type {string}
     * @memberof ModifyDashboardDto
     */
    dashboard?: string;
}

/**
 * Check if a given object implements the ModifyDashboardDto interface.
 */
export function instanceOfModifyDashboardDto(value: object): value is ModifyDashboardDto {
    return true;
}

export function ModifyDashboardDtoFromJSON(json: any): ModifyDashboardDto {
    return ModifyDashboardDtoFromJSONTyped(json, false);
}

export function ModifyDashboardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyDashboardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'dashboard': json['dashboard'] == null ? undefined : json['dashboard'],
    };
}

export function ModifyDashboardDtoToJSON(value?: ModifyDashboardDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dashboard': value['dashboard'],
    };
}

