/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModifyActionDto } from './ModifyActionDto';
import {
    ModifyActionDtoFromJSON,
    ModifyActionDtoFromJSONTyped,
    ModifyActionDtoToJSON,
} from './ModifyActionDto';

/**
 * 
 * @export
 * @interface ModifyActionRequest
 */
export interface ModifyActionRequest {
    /**
     * 
     * @type {ModifyActionDto}
     * @memberof ModifyActionRequest
     */
    request: ModifyActionDto;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof ModifyActionRequest
     */
    fileList?: Array<Blob>;
}

/**
 * Check if a given object implements the ModifyActionRequest interface.
 */
export function instanceOfModifyActionRequest(value: object): value is ModifyActionRequest {
    if (!('request' in value) || value['request'] === undefined) return false;
    return true;
}

export function ModifyActionRequestFromJSON(json: any): ModifyActionRequest {
    return ModifyActionRequestFromJSONTyped(json, false);
}

export function ModifyActionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyActionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'request': ModifyActionDtoFromJSON(json['request']),
        'fileList': json['fileList'] == null ? undefined : json['fileList'],
    };
}

export function ModifyActionRequestToJSON(value?: ModifyActionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request': ModifyActionDtoToJSON(value['request']),
        'fileList': value['fileList'],
    };
}

