/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModifyMediaListDto
 */
export interface ModifyMediaListDto {
    /**
     * 타이틀
     * @type {string}
     * @memberof ModifyMediaListDto
     */
    title: string;
    /**
     * 프로젝트ID
     * @type {number}
     * @memberof ModifyMediaListDto
     */
    projectId?: number;
    /**
     * 공유 설정
     * @type {string}
     * @memberof ModifyMediaListDto
     */
    shareCode?: string;
    /**
     * 소유자ID
     * @type {number}
     * @memberof ModifyMediaListDto
     */
    ownerId?: number;
    /**
     * 현재 선택된 사용자의 그룹ID
     * @type {number}
     * @memberof ModifyMediaListDto
     */
    groupId: number;
}

/**
 * Check if a given object implements the ModifyMediaListDto interface.
 */
export function instanceOfModifyMediaListDto(value: object): value is ModifyMediaListDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function ModifyMediaListDtoFromJSON(json: any): ModifyMediaListDto {
    return ModifyMediaListDtoFromJSONTyped(json, false);
}

export function ModifyMediaListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyMediaListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'shareCode': json['shareCode'] == null ? undefined : json['shareCode'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'groupId': json['groupId'],
    };
}

export function ModifyMediaListDtoToJSON(value?: ModifyMediaListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'projectId': value['projectId'],
        'shareCode': value['shareCode'],
        'ownerId': value['ownerId'],
        'groupId': value['groupId'],
    };
}

