/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModifyCompanyDto
 */
export interface ModifyCompanyDto {
    /**
     * 회사 분류, 공통코드 - COM_CATEGORY 
     * @type {string}
     * @memberof ModifyCompanyDto
     */
    categoryCode?: string;
    /**
     * 대표이름
     * @type {string}
     * @memberof ModifyCompanyDto
     */
    ceoName?: string;
    /**
     * 사업자등록번호
     * @type {string}
     * @memberof ModifyCompanyDto
     */
    bizRegisNo?: string;
    /**
     * 직원수, 공통코드 - COM_TOTAL_MEMBERS 
     * @type {string}
     * @memberof ModifyCompanyDto
     */
    totalMembers?: string;
    /**
     * 웹사이트주소
     * @type {string}
     * @memberof ModifyCompanyDto
     */
    wsite?: string;
    /**
     * 국가 코드, 공통코드 - COM_COUNTRY
     * @type {string}
     * @memberof ModifyCompanyDto
     */
    countryCode?: string;
    /**
     * 주소 or 외국 주소
     * @type {string}
     * @memberof ModifyCompanyDto
     */
    address?: string;
    /**
     * 상세주소
     * @type {string}
     * @memberof ModifyCompanyDto
     */
    detailedAddress?: string;
    /**
     * 우편번호
     * @type {string}
     * @memberof ModifyCompanyDto
     */
    zipCode?: string;
    /**
     * 삭제된 파일 ID 목록 - 회사 상세 정보에서 관련 파일ID
     * @type {Array<number>}
     * @memberof ModifyCompanyDto
     */
    deletedAttachIdList?: Array<number>;
}

/**
 * Check if a given object implements the ModifyCompanyDto interface.
 */
export function instanceOfModifyCompanyDto(value: object): value is ModifyCompanyDto {
    return true;
}

export function ModifyCompanyDtoFromJSON(json: any): ModifyCompanyDto {
    return ModifyCompanyDtoFromJSONTyped(json, false);
}

export function ModifyCompanyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyCompanyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryCode': json['categoryCode'] == null ? undefined : json['categoryCode'],
        'ceoName': json['ceoName'] == null ? undefined : json['ceoName'],
        'bizRegisNo': json['bizRegisNo'] == null ? undefined : json['bizRegisNo'],
        'totalMembers': json['totalMembers'] == null ? undefined : json['totalMembers'],
        'wsite': json['wsite'] == null ? undefined : json['wsite'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'address': json['address'] == null ? undefined : json['address'],
        'detailedAddress': json['detailedAddress'] == null ? undefined : json['detailedAddress'],
        'zipCode': json['zipCode'] == null ? undefined : json['zipCode'],
        'deletedAttachIdList': json['deletedAttachIdList'] == null ? undefined : json['deletedAttachIdList'],
    };
}

export function ModifyCompanyDtoToJSON(value?: ModifyCompanyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'categoryCode': value['categoryCode'],
        'ceoName': value['ceoName'],
        'bizRegisNo': value['bizRegisNo'],
        'totalMembers': value['totalMembers'],
        'wsite': value['wsite'],
        'countryCode': value['countryCode'],
        'address': value['address'],
        'detailedAddress': value['detailedAddress'],
        'zipCode': value['zipCode'],
        'deletedAttachIdList': value['deletedAttachIdList'],
    };
}

