/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModifyCompanyDto } from './ModifyCompanyDto';
import {
    ModifyCompanyDtoFromJSON,
    ModifyCompanyDtoFromJSONTyped,
    ModifyCompanyDtoToJSON,
} from './ModifyCompanyDto';

/**
 * 
 * @export
 * @interface ModifyCompanyRequest
 */
export interface ModifyCompanyRequest {
    /**
     * 
     * @type {ModifyCompanyDto}
     * @memberof ModifyCompanyRequest
     */
    request: ModifyCompanyDto;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof ModifyCompanyRequest
     */
    fileList?: Array<Blob>;
}

/**
 * Check if a given object implements the ModifyCompanyRequest interface.
 */
export function instanceOfModifyCompanyRequest(value: object): value is ModifyCompanyRequest {
    if (!('request' in value) || value['request'] === undefined) return false;
    return true;
}

export function ModifyCompanyRequestFromJSON(json: any): ModifyCompanyRequest {
    return ModifyCompanyRequestFromJSONTyped(json, false);
}

export function ModifyCompanyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyCompanyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'request': ModifyCompanyDtoFromJSON(json['request']),
        'fileList': json['fileList'] == null ? undefined : json['fileList'],
    };
}

export function ModifyCompanyRequestToJSON(value?: ModifyCompanyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'request': ModifyCompanyDtoToJSON(value['request']),
        'fileList': value['fileList'],
    };
}

