/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModifyMediaSrchDto
 */
export interface ModifyMediaSrchDto {
    /**
     * 
     * @type {string}
     * @memberof ModifyMediaSrchDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ModifyMediaSrchDto
     */
    shareCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ModifyMediaSrchDto
     */
    shareTargetCode?: string;
    /**
     * 
     * @type {number}
     * @memberof ModifyMediaSrchDto
     */
    groupId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModifyMediaSrchDto
     */
    conditions?: string;
    /**
     * 소유자ID
     * @type {number}
     * @memberof ModifyMediaSrchDto
     */
    ownerId?: number;
}

/**
 * Check if a given object implements the ModifyMediaSrchDto interface.
 */
export function instanceOfModifyMediaSrchDto(value: object): value is ModifyMediaSrchDto {
    return true;
}

export function ModifyMediaSrchDtoFromJSON(json: any): ModifyMediaSrchDto {
    return ModifyMediaSrchDtoFromJSONTyped(json, false);
}

export function ModifyMediaSrchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyMediaSrchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'shareCode': json['shareCode'] == null ? undefined : json['shareCode'],
        'shareTargetCode': json['shareTargetCode'] == null ? undefined : json['shareTargetCode'],
        'groupId': json['groupId'] == null ? undefined : json['groupId'],
        'conditions': json['conditions'] == null ? undefined : json['conditions'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
    };
}

export function ModifyMediaSrchDtoToJSON(value?: ModifyMediaSrchDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'shareCode': value['shareCode'],
        'shareTargetCode': value['shareTargetCode'],
        'groupId': value['groupId'],
        'conditions': value['conditions'],
        'ownerId': value['ownerId'],
    };
}

