/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModifyClipBookDto
 */
export interface ModifyClipBookDto {
    /**
     * 클립북 유형
     * @type {string}
     * @memberof ModifyClipBookDto
     */
    type: string;
    /**
     * 타이틀
     * @type {string}
     * @memberof ModifyClipBookDto
     */
    title: string;
    /**
     * COVERAGE 클립북인 경우 prId(MailingId) 목록
     * @type {Array<number>}
     * @memberof ModifyClipBookDto
     */
    prIdList?: Array<number>;
    /**
     * 프로젝트ID
     * @type {number}
     * @memberof ModifyClipBookDto
     */
    projectId?: number;
    /**
     * 공유 설정
     * @type {string}
     * @memberof ModifyClipBookDto
     */
    shareCode?: string;
    /**
     * 소유자
     * @type {number}
     * @memberof ModifyClipBookDto
     */
    ownerId?: number;
}

/**
 * Check if a given object implements the ModifyClipBookDto interface.
 */
export function instanceOfModifyClipBookDto(value: object): value is ModifyClipBookDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ModifyClipBookDtoFromJSON(json: any): ModifyClipBookDto {
    return ModifyClipBookDtoFromJSONTyped(json, false);
}

export function ModifyClipBookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyClipBookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
        'prIdList': json['prIdList'] == null ? undefined : json['prIdList'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'shareCode': json['shareCode'] == null ? undefined : json['shareCode'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
    };
}

export function ModifyClipBookDtoToJSON(value?: ModifyClipBookDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'title': value['title'],
        'prIdList': value['prIdList'],
        'projectId': value['projectId'],
        'shareCode': value['shareCode'],
        'ownerId': value['ownerId'],
    };
}

