/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 회원 수정 정보
 * @export
 * @interface ModifyUserFirstDto
 */
export interface ModifyUserFirstDto {
    /**
     * 이름
     * @type {string}
     * @memberof ModifyUserFirstDto
     */
    name: string;
    /**
     * 표시이름
     * @type {string}
     * @memberof ModifyUserFirstDto
     */
    nickname?: string;
    /**
     * 비밀번호
     * @type {string}
     * @memberof ModifyUserFirstDto
     */
    passwd: string;
    /**
     * 부서
     * @type {string}
     * @memberof ModifyUserFirstDto
     */
    department?: string;
    /**
     * 직책
     * @type {string}
     * @memberof ModifyUserFirstDto
     */
    position?: string;
    /**
     * 휴대폰
     * @type {string}
     * @memberof ModifyUserFirstDto
     */
    mobile?: string;
    /**
     * 전화번호
     * @type {string}
     * @memberof ModifyUserFirstDto
     */
    phone?: string;
    /**
     * 뉴스레터수신 여부
     * @type {boolean}
     * @memberof ModifyUserFirstDto
     */
    receiveLetter: boolean;
}

/**
 * Check if a given object implements the ModifyUserFirstDto interface.
 */
export function instanceOfModifyUserFirstDto(value: object): value is ModifyUserFirstDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('passwd' in value) || value['passwd'] === undefined) return false;
    if (!('receiveLetter' in value) || value['receiveLetter'] === undefined) return false;
    return true;
}

export function ModifyUserFirstDtoFromJSON(json: any): ModifyUserFirstDto {
    return ModifyUserFirstDtoFromJSONTyped(json, false);
}

export function ModifyUserFirstDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyUserFirstDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'passwd': json['passwd'],
        'department': json['department'] == null ? undefined : json['department'],
        'position': json['position'] == null ? undefined : json['position'],
        'mobile': json['mobile'] == null ? undefined : json['mobile'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'receiveLetter': json['receiveLetter'],
    };
}

export function ModifyUserFirstDtoToJSON(value?: ModifyUserFirstDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'nickname': value['nickname'],
        'passwd': value['passwd'],
        'department': value['department'],
        'position': value['position'],
        'mobile': value['mobile'],
        'phone': value['phone'],
        'receiveLetter': value['receiveLetter'],
    };
}

