/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NameValue
 */
export interface NameValue {
    /**
     * 
     * @type {string}
     * @memberof NameValue
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof NameValue
     */
    value?: number;
}

/**
 * Check if a given object implements the NameValue interface.
 */
export function instanceOfNameValue(value: object): value is NameValue {
    return true;
}

export function NameValueFromJSON(json: any): NameValue {
    return NameValueFromJSONTyped(json, false);
}

export function NameValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameValue {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function NameValueToJSON(value?: NameValue | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

