/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { ActionDtoForList } from './ActionDtoForList';
import {
    ActionDtoForListFromJSON,
    ActionDtoForListFromJSONTyped,
    ActionDtoForListToJSON,
} from './ActionDtoForList';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageActionDtoForList
 */
export interface PageActionDtoForList {
    /**
     * 
     * @type {number}
     * @memberof PageActionDtoForList
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageActionDtoForList
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageActionDtoForList
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageActionDtoForList
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageActionDtoForList
     */
    size?: number;
    /**
     * 
     * @type {Array<ActionDtoForList>}
     * @memberof PageActionDtoForList
     */
    content?: Array<ActionDtoForList>;
    /**
     * 
     * @type {number}
     * @memberof PageActionDtoForList
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageActionDtoForList
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageActionDtoForList
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageActionDtoForList
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageActionDtoForList
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageActionDtoForList interface.
 */
export function instanceOfPageActionDtoForList(value: object): value is PageActionDtoForList {
    return true;
}

export function PageActionDtoForListFromJSON(json: any): PageActionDtoForList {
    return PageActionDtoForListFromJSONTyped(json, false);
}

export function PageActionDtoForListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageActionDtoForList {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ActionDtoForListFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageActionDtoForListToJSON(value?: PageActionDtoForList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'first': value['first'],
        'last': value['last'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ActionDtoForListToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

