/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';
import type { JrnlstListDto } from './JrnlstListDto';
import {
    JrnlstListDtoFromJSON,
    JrnlstListDtoFromJSONTyped,
    JrnlstListDtoToJSON,
} from './JrnlstListDto';

/**
 * 
 * @export
 * @interface PageJrnlstListDto
 */
export interface PageJrnlstListDto {
    /**
     * 
     * @type {number}
     * @memberof PageJrnlstListDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageJrnlstListDto
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageJrnlstListDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageJrnlstListDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageJrnlstListDto
     */
    size?: number;
    /**
     * 
     * @type {Array<JrnlstListDto>}
     * @memberof PageJrnlstListDto
     */
    content?: Array<JrnlstListDto>;
    /**
     * 
     * @type {number}
     * @memberof PageJrnlstListDto
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageJrnlstListDto
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageJrnlstListDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageJrnlstListDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageJrnlstListDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageJrnlstListDto interface.
 */
export function instanceOfPageJrnlstListDto(value: object): value is PageJrnlstListDto {
    return true;
}

export function PageJrnlstListDtoFromJSON(json: any): PageJrnlstListDto {
    return PageJrnlstListDtoFromJSONTyped(json, false);
}

export function PageJrnlstListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageJrnlstListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(JrnlstListDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageJrnlstListDtoToJSON(value?: PageJrnlstListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'first': value['first'],
        'last': value['last'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(JrnlstListDtoToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

