/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { PayRequestForListDto } from './PayRequestForListDto';
import {
    PayRequestForListDtoFromJSON,
    PayRequestForListDtoFromJSONTyped,
    PayRequestForListDtoToJSON,
} from './PayRequestForListDto';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PagePayRequestForListDto
 */
export interface PagePayRequestForListDto {
    /**
     * 
     * @type {number}
     * @memberof PagePayRequestForListDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagePayRequestForListDto
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PagePayRequestForListDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagePayRequestForListDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PagePayRequestForListDto
     */
    size?: number;
    /**
     * 
     * @type {Array<PayRequestForListDto>}
     * @memberof PagePayRequestForListDto
     */
    content?: Array<PayRequestForListDto>;
    /**
     * 
     * @type {number}
     * @memberof PagePayRequestForListDto
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PagePayRequestForListDto
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PagePayRequestForListDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PagePayRequestForListDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PagePayRequestForListDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PagePayRequestForListDto interface.
 */
export function instanceOfPagePayRequestForListDto(value: object): value is PagePayRequestForListDto {
    return true;
}

export function PagePayRequestForListDtoFromJSON(json: any): PagePayRequestForListDto {
    return PagePayRequestForListDtoFromJSONTyped(json, false);
}

export function PagePayRequestForListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagePayRequestForListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(PayRequestForListDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PagePayRequestForListDtoToJSON(value?: PagePayRequestForListDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'first': value['first'],
        'last': value['last'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(PayRequestForListDtoToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

