/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { FileAttachDto } from './FileAttachDto';
import {
    FileAttachDtoFromJSON,
    FileAttachDtoFromJSONTyped,
    FileAttachDtoToJSON,
} from './FileAttachDto';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageFileAttachDto
 */
export interface PageFileAttachDto {
    /**
     * 
     * @type {number}
     * @memberof PageFileAttachDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageFileAttachDto
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageFileAttachDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageFileAttachDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageFileAttachDto
     */
    size?: number;
    /**
     * 
     * @type {Array<FileAttachDto>}
     * @memberof PageFileAttachDto
     */
    content?: Array<FileAttachDto>;
    /**
     * 
     * @type {number}
     * @memberof PageFileAttachDto
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageFileAttachDto
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageFileAttachDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageFileAttachDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageFileAttachDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageFileAttachDto interface.
 */
export function instanceOfPageFileAttachDto(value: object): value is PageFileAttachDto {
    return true;
}

export function PageFileAttachDtoFromJSON(json: any): PageFileAttachDto {
    return PageFileAttachDtoFromJSONTyped(json, false);
}

export function PageFileAttachDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageFileAttachDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(FileAttachDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageFileAttachDtoToJSON(value?: PageFileAttachDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'first': value['first'],
        'last': value['last'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(FileAttachDtoToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

