/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonCodeDto } from './CommonCodeDto';
import {
    CommonCodeDtoFromJSON,
    CommonCodeDtoFromJSONTyped,
    CommonCodeDtoToJSON,
} from './CommonCodeDto';

/**
 * 
 * @export
 * @interface PreLoadCommonCodeDto
 */
export interface PreLoadCommonCodeDto {
    /**
     * 
     * @type {number}
     * @memberof PreLoadCommonCodeDto
     */
    parentId?: number;
    /**
     * 
     * @type {string}
     * @memberof PreLoadCommonCodeDto
     */
    parentCode?: string;
    /**
     * 
     * @type {number}
     * @memberof PreLoadCommonCodeDto
     */
    parentCommonCodeId?: number;
    /**
     * 
     * @type {Array<CommonCodeDto>}
     * @memberof PreLoadCommonCodeDto
     */
    commonCodeList?: Array<CommonCodeDto>;
}

/**
 * Check if a given object implements the PreLoadCommonCodeDto interface.
 */
export function instanceOfPreLoadCommonCodeDto(value: object): value is PreLoadCommonCodeDto {
    return true;
}

export function PreLoadCommonCodeDtoFromJSON(json: any): PreLoadCommonCodeDto {
    return PreLoadCommonCodeDtoFromJSONTyped(json, false);
}

export function PreLoadCommonCodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreLoadCommonCodeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'parentCode': json['parentCode'] == null ? undefined : json['parentCode'],
        'parentCommonCodeId': json['parentCommonCodeId'] == null ? undefined : json['parentCommonCodeId'],
        'commonCodeList': json['commonCodeList'] == null ? undefined : ((json['commonCodeList'] as Array<any>).map(CommonCodeDtoFromJSON)),
    };
}

export function PreLoadCommonCodeDtoToJSON(value?: PreLoadCommonCodeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'parentId': value['parentId'],
        'parentCode': value['parentCode'],
        'parentCommonCodeId': value['parentCommonCodeId'],
        'commonCodeList': value['commonCodeList'] == null ? undefined : ((value['commonCodeList'] as Array<any>).map(CommonCodeDtoToJSON)),
    };
}

