/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestConfirmOtpDto
 */
export interface RequestConfirmOtpDto {
    /**
     * OTP 코드 확인 요청
     * @type {string}
     * @memberof RequestConfirmOtpDto
     */
    otp: string;
}

/**
 * Check if a given object implements the RequestConfirmOtpDto interface.
 */
export function instanceOfRequestConfirmOtpDto(value: object): value is RequestConfirmOtpDto {
    if (!('otp' in value) || value['otp'] === undefined) return false;
    return true;
}

export function RequestConfirmOtpDtoFromJSON(json: any): RequestConfirmOtpDto {
    return RequestConfirmOtpDtoFromJSONTyped(json, false);
}

export function RequestConfirmOtpDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestConfirmOtpDto {
    if (json == null) {
        return json;
    }
    return {
        
        'otp': json['otp'],
    };
}

export function RequestConfirmOtpDtoToJSON(value?: RequestConfirmOtpDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'otp': value['otp'],
    };
}

