/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaggingTargetDto } from './TaggingTargetDto';
import {
    TaggingTargetDtoFromJSON,
    TaggingTargetDtoFromJSONTyped,
    TaggingTargetDtoToJSON,
} from './TaggingTargetDto';

/**
 * 
 * @export
 * @interface RequestTaggingDto
 */
export interface RequestTaggingDto {
    /**
     * 구분값 : NEWS(뉴스) / ACTION(활동) / NEWSWIRE(뉴스와이어) 구분값 
     * @type {string}
     * @memberof RequestTaggingDto
     */
    category: string;
    /**
     * 태그ID 목록
     * @type {Array<number>}
     * @memberof RequestTaggingDto
     */
    tagIdList: Array<number>;
    /**
     * newsId / actionId / nwReleaseId 등 대상 id 값 목록
     * @type {Array<TaggingTargetDto>}
     * @memberof RequestTaggingDto
     */
    targetList: Array<TaggingTargetDto>;
}

/**
 * Check if a given object implements the RequestTaggingDto interface.
 */
export function instanceOfRequestTaggingDto(value: object): value is RequestTaggingDto {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('tagIdList' in value) || value['tagIdList'] === undefined) return false;
    if (!('targetList' in value) || value['targetList'] === undefined) return false;
    return true;
}

export function RequestTaggingDtoFromJSON(json: any): RequestTaggingDto {
    return RequestTaggingDtoFromJSONTyped(json, false);
}

export function RequestTaggingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestTaggingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'tagIdList': json['tagIdList'],
        'targetList': ((json['targetList'] as Array<any>).map(TaggingTargetDtoFromJSON)),
    };
}

export function RequestTaggingDtoToJSON(value?: RequestTaggingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'category': value['category'],
        'tagIdList': value['tagIdList'],
        'targetList': ((value['targetList'] as Array<any>).map(TaggingTargetDtoToJSON)),
    };
}

