/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestMailingDto
 */
export interface RequestMailingDto {
    /**
     * 선택된 그룹 ID, 공유 대상이 이그룹인 경우에 조건으로 처리
     * @type {number}
     * @memberof RequestMailingDto
     */
    groupId: number;
}

/**
 * Check if a given object implements the RequestMailingDto interface.
 */
export function instanceOfRequestMailingDto(value: object): value is RequestMailingDto {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function RequestMailingDtoFromJSON(json: any): RequestMailingDto {
    return RequestMailingDtoFromJSONTyped(json, false);
}

export function RequestMailingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestMailingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
    };
}

export function RequestMailingDtoToJSON(value?: RequestMailingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupId': value['groupId'],
    };
}

