/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestActionExcelDto
 */
export interface RequestActionExcelDto {
    /**
     * 선택된 그룹 ID
     * @type {number}
     * @memberof RequestActionExcelDto
     */
    groupId: number;
    /**
     * 활동 ID 목록
     * @type {Array<number>}
     * @memberof RequestActionExcelDto
     */
    actionIdList?: Array<number>;
}

/**
 * Check if a given object implements the RequestActionExcelDto interface.
 */
export function instanceOfRequestActionExcelDto(value: object): value is RequestActionExcelDto {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function RequestActionExcelDtoFromJSON(json: any): RequestActionExcelDto {
    return RequestActionExcelDtoFromJSONTyped(json, false);
}

export function RequestActionExcelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestActionExcelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'actionIdList': json['actionIdList'] == null ? undefined : json['actionIdList'],
    };
}

export function RequestActionExcelDtoToJSON(value?: RequestActionExcelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupId': value['groupId'],
        'actionIdList': value['actionIdList'],
    };
}

