/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestJournalistByNewsDto
 */
export interface RequestJournalistByNewsDto {
    /**
     * JournalistId 배열
     * @type {Array<number>}
     * @memberof RequestJournalistByNewsDto
     */
    journalistIdList: Array<number>;
    /**
     * 뉴스
     * @type {string}
     * @memberof RequestJournalistByNewsDto
     */
    news?: string;
}

/**
 * Check if a given object implements the RequestJournalistByNewsDto interface.
 */
export function instanceOfRequestJournalistByNewsDto(value: object): value is RequestJournalistByNewsDto {
    if (!('journalistIdList' in value) || value['journalistIdList'] === undefined) return false;
    return true;
}

export function RequestJournalistByNewsDtoFromJSON(json: any): RequestJournalistByNewsDto {
    return RequestJournalistByNewsDtoFromJSONTyped(json, false);
}

export function RequestJournalistByNewsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestJournalistByNewsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'journalistIdList': json['journalistIdList'],
        'news': json['news'] == null ? undefined : json['news'],
    };
}

export function RequestJournalistByNewsDtoToJSON(value?: RequestJournalistByNewsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'journalistIdList': value['journalistIdList'],
        'news': value['news'],
    };
}

