/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestNewswireReleaseDto
 */
export interface RequestNewswireReleaseDto {
    /**
     * 선택된 그룹 ID, 공유 대상이 이그룹인 경우에 조건으로 처리
     * @type {number}
     * @memberof RequestNewswireReleaseDto
     */
    groupId: number;
}

/**
 * Check if a given object implements the RequestNewswireReleaseDto interface.
 */
export function instanceOfRequestNewswireReleaseDto(value: object): value is RequestNewswireReleaseDto {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function RequestNewswireReleaseDtoFromJSON(json: any): RequestNewswireReleaseDto {
    return RequestNewswireReleaseDtoFromJSONTyped(json, false);
}

export function RequestNewswireReleaseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestNewswireReleaseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
    };
}

export function RequestNewswireReleaseDtoToJSON(value?: RequestNewswireReleaseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupId': value['groupId'],
    };
}

