/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestMediaSrchDto
 */
export interface RequestMediaSrchDto {
    /**
     * 그룹 ID, 공유 대상이 이그룹인 경우에 조건으로 처리
     * @type {number}
     * @memberof RequestMediaSrchDto
     */
    groupId: number;
}

/**
 * Check if a given object implements the RequestMediaSrchDto interface.
 */
export function instanceOfRequestMediaSrchDto(value: object): value is RequestMediaSrchDto {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function RequestMediaSrchDtoFromJSON(json: any): RequestMediaSrchDto {
    return RequestMediaSrchDtoFromJSONTyped(json, false);
}

export function RequestMediaSrchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestMediaSrchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
    };
}

export function RequestMediaSrchDtoToJSON(value?: RequestMediaSrchDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupId': value['groupId'],
    };
}

