/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestBlockedUserDto
 */
export interface RequestBlockedUserDto {
    /**
     * from Email
     * @type {string}
     * @memberof RequestBlockedUserDto
     */
    fr: string;
    /**
     * to Email
     * @type {string}
     * @memberof RequestBlockedUserDto
     */
    to: string;
    /**
     * mailing receive key 
     * @type {string}
     * @memberof RequestBlockedUserDto
     */
    key?: string;
}

/**
 * Check if a given object implements the RequestBlockedUserDto interface.
 */
export function instanceOfRequestBlockedUserDto(value: object): value is RequestBlockedUserDto {
    if (!('fr' in value) || value['fr'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function RequestBlockedUserDtoFromJSON(json: any): RequestBlockedUserDto {
    return RequestBlockedUserDtoFromJSONTyped(json, false);
}

export function RequestBlockedUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBlockedUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'fr': json['fr'],
        'to': json['to'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function RequestBlockedUserDtoToJSON(value?: RequestBlockedUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fr': value['fr'],
        'to': value['to'],
        'key': value['key'],
    };
}

