/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestMediaExcelDto
 */
export interface RequestMediaExcelDto {
    /**
     * MediaId 배열
     * @type {Array<number>}
     * @memberof RequestMediaExcelDto
     */
    mediaIdList: Array<number>;
}

/**
 * Check if a given object implements the RequestMediaExcelDto interface.
 */
export function instanceOfRequestMediaExcelDto(value: object): value is RequestMediaExcelDto {
    if (!('mediaIdList' in value) || value['mediaIdList'] === undefined) return false;
    return true;
}

export function RequestMediaExcelDtoFromJSON(json: any): RequestMediaExcelDto {
    return RequestMediaExcelDtoFromJSONTyped(json, false);
}

export function RequestMediaExcelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestMediaExcelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaIdList': json['mediaIdList'],
    };
}

export function RequestMediaExcelDtoToJSON(value?: RequestMediaExcelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mediaIdList': value['mediaIdList'],
    };
}

