/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 비밀번호 변경
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordDto
     */
    email: string;
    /**
     * 새로운 비밀번호
     * @type {string}
     * @memberof ResetPasswordDto
     */
    newPassword: string;
    /**
     * 새로운 비밀번호 확인, 빈값인 경우 newPassword 값이 이전 패스워드와 동일한지 체크함
     * @type {string}
     * @memberof ResetPasswordDto
     */
    newPasswordConfirm: string;
}

/**
 * Check if a given object implements the ResetPasswordDto interface.
 */
export function instanceOfResetPasswordDto(value: object): value is ResetPasswordDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('newPasswordConfirm' in value) || value['newPasswordConfirm'] === undefined) return false;
    return true;
}

export function ResetPasswordDtoFromJSON(json: any): ResetPasswordDto {
    return ResetPasswordDtoFromJSONTyped(json, false);
}

export function ResetPasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'newPassword': json['newPassword'],
        'newPasswordConfirm': json['newPasswordConfirm'],
    };
}

export function ResetPasswordDtoToJSON(value?: ResetPasswordDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'newPassword': value['newPassword'],
        'newPasswordConfirm': value['newPasswordConfirm'],
    };
}

