/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseListCountDto
 */
export interface ResponseListCountDto {
    /**
     * 
     * @type {number}
     * @memberof ResponseListCountDto
     */
    mediaCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponseListCountDto
     */
    journalistCount?: number;
}

/**
 * Check if a given object implements the ResponseListCountDto interface.
 */
export function instanceOfResponseListCountDto(value: object): value is ResponseListCountDto {
    return true;
}

export function ResponseListCountDtoFromJSON(json: any): ResponseListCountDto {
    return ResponseListCountDtoFromJSONTyped(json, false);
}

export function ResponseListCountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListCountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaCount': json['mediaCount'] == null ? undefined : json['mediaCount'],
        'journalistCount': json['journalistCount'] == null ? undefined : json['journalistCount'],
    };
}

export function ResponseListCountDtoToJSON(value?: ResponseListCountDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mediaCount': value['mediaCount'],
        'journalistCount': value['journalistCount'],
    };
}

