/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewsDocumentSimpleDto } from './NewsDocumentSimpleDto';
import {
    NewsDocumentSimpleDtoFromJSON,
    NewsDocumentSimpleDtoFromJSONTyped,
    NewsDocumentSimpleDtoToJSON,
} from './NewsDocumentSimpleDto';

/**
 * 
 * @export
 * @interface ResponseJournalistNewsDto
 */
export interface ResponseJournalistNewsDto {
    /**
     * JournalistId
     * @type {number}
     * @memberof ResponseJournalistNewsDto
     */
    journalistId: number;
    /**
     * 뉴스 목록
     * @type {Array<NewsDocumentSimpleDto>}
     * @memberof ResponseJournalistNewsDto
     */
    newsList?: Array<NewsDocumentSimpleDto>;
}

/**
 * Check if a given object implements the ResponseJournalistNewsDto interface.
 */
export function instanceOfResponseJournalistNewsDto(value: object): value is ResponseJournalistNewsDto {
    if (!('journalistId' in value) || value['journalistId'] === undefined) return false;
    return true;
}

export function ResponseJournalistNewsDtoFromJSON(json: any): ResponseJournalistNewsDto {
    return ResponseJournalistNewsDtoFromJSONTyped(json, false);
}

export function ResponseJournalistNewsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseJournalistNewsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'journalistId': json['journalistId'],
        'newsList': json['newsList'] == null ? undefined : ((json['newsList'] as Array<any>).map(NewsDocumentSimpleDtoFromJSON)),
    };
}

export function ResponseJournalistNewsDtoToJSON(value?: ResponseJournalistNewsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'journalistId': value['journalistId'],
        'newsList': value['newsList'] == null ? undefined : ((value['newsList'] as Array<any>).map(NewsDocumentSimpleDtoToJSON)),
    };
}

