/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseShortUrlDto
 */
export interface ResponseShortUrlDto {
    /**
     * 
     * @type {number}
     * @memberof ResponseShortUrlDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponseShortUrlDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseShortUrlDto
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseShortUrlDto
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseShortUrlDto
     */
    objectType?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseShortUrlDto
     */
    originUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseShortUrlDto
     */
    timeout?: string;
}

/**
 * Check if a given object implements the ResponseShortUrlDto interface.
 */
export function instanceOfResponseShortUrlDto(value: object): value is ResponseShortUrlDto {
    return true;
}

export function ResponseShortUrlDtoFromJSON(json: any): ResponseShortUrlDto {
    return ResponseShortUrlDtoFromJSONTyped(json, false);
}

export function ResponseShortUrlDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseShortUrlDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'company': json['company'] == null ? undefined : json['company'],
        'type': json['type'] == null ? undefined : json['type'],
        'objectType': json['objectType'] == null ? undefined : json['objectType'],
        'originUrl': json['originUrl'] == null ? undefined : json['originUrl'],
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
    };
}

export function ResponseShortUrlDtoToJSON(value?: ResponseShortUrlDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
        'company': value['company'],
        'type': value['type'],
        'objectType': value['objectType'],
        'originUrl': value['originUrl'],
        'timeout': value['timeout'],
    };
}

