/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultNewsInfo
 */
export interface ResultNewsInfo {
    /**
     * 
     * @type {string}
     * @memberof ResultNewsInfo
     */
    media?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultNewsInfo
     */
    mediaId?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultNewsInfo
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultNewsInfo
     */
    reporter?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultNewsInfo
     */
    date?: string;
}

/**
 * Check if a given object implements the ResultNewsInfo interface.
 */
export function instanceOfResultNewsInfo(value: object): value is ResultNewsInfo {
    return true;
}

export function ResultNewsInfoFromJSON(json: any): ResultNewsInfo {
    return ResultNewsInfoFromJSONTyped(json, false);
}

export function ResultNewsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultNewsInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'media': json['media'] == null ? undefined : json['media'],
        'mediaId': json['mediaId'] == null ? undefined : json['mediaId'],
        'title': json['title'] == null ? undefined : json['title'],
        'reporter': json['reporter'] == null ? undefined : json['reporter'],
        'date': json['date'] == null ? undefined : json['date'],
    };
}

export function ResultNewsInfoToJSON(value?: ResultNewsInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'media': value['media'],
        'mediaId': value['mediaId'],
        'title': value['title'],
        'reporter': value['reporter'],
        'date': value['date'],
    };
}

