/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 스케줄 표시 데이터
 * @export
 * @interface ScheduleDisplayDto
 */
export interface ScheduleDisplayDto {
    /**
     * 요일별 시간 목록
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ScheduleDisplayDto
     */
    scheduleByDay?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the ScheduleDisplayDto interface.
 */
export function instanceOfScheduleDisplayDto(value: object): value is ScheduleDisplayDto {
    return true;
}

export function ScheduleDisplayDtoFromJSON(json: any): ScheduleDisplayDto {
    return ScheduleDisplayDtoFromJSONTyped(json, false);
}

export function ScheduleDisplayDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleDisplayDto {
    if (json == null) {
        return json;
    }
    return {
        
        'scheduleByDay': json['scheduleByDay'] == null ? undefined : json['scheduleByDay'],
    };
}

export function ScheduleDisplayDtoToJSON(value?: ScheduleDisplayDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'scheduleByDay': value['scheduleByDay'],
    };
}

