/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchActionDto
 */
export interface SearchActionDto {
    /**
     * Title
     * @type {string}
     * @memberof SearchActionDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchActionDto
     */
    shareCode?: string;
    /**
     * 그룹 ID
     * @type {number}
     * @memberof SearchActionDto
     */
    groupId: number;
    /**
     * 유형 목록, 공통코드 ACTION_CATEGORY 
     * @type {Array<string>}
     * @memberof SearchActionDto
     */
    categoryList?: Array<string>;
    /**
     * 상태 필터 목록, 공통코드 ACTION_STATE_FILTER : DRA / RES / PRO / FIN
     * @type {Array<string>}
     * @memberof SearchActionDto
     */
    state_filter?: Array<string>;
    /**
     * 뉴스와이어 상태 목록, 공통코드 NEWSWIRE_STATE : DRA_DRAFT / PRO_SUBMIT / FIN_REJECT / FIN_PUBLISHED / FIN_NEWSWIRE_DEL
     * @type {Array<string>}
     * @memberof SearchActionDto
     */
    state?: Array<string>;
    /**
     * 소유자ID 목록
     * @type {Array<number>}
     * @memberof SearchActionDto
     */
    ownerIdList?: Array<number>;
    /**
     * 태그ID 목록
     * @type {Array<number>}
     * @memberof SearchActionDto
     */
    tagIdList?: Array<number>;
    /**
     * 미디어ID 목록
     * @type {Array<number>}
     * @memberof SearchActionDto
     */
    mediaIdList?: Array<number>;
    /**
     * 언론인ID 목록
     * @type {Array<number>}
     * @memberof SearchActionDto
     */
    journalistIdList?: Array<number>;
    /**
     * 시간대 타임존,  Asia/Seoul 
     * @type {string}
     * @memberof SearchActionDto
     */
    timezone?: string;
    /**
     * 기간에 따른 시작 연,월,일과 종료 연,월,일
     * @type {string}
     * @memberof SearchActionDto
     */
    periodStartYear?: string;
    /**
     * 시작 월
     * @type {string}
     * @memberof SearchActionDto
     */
    periodStartMonth?: string;
    /**
     * 시작 일
     * @type {string}
     * @memberof SearchActionDto
     */
    periodStartDay?: string;
    /**
     * 기간에 따른 종료 연,월,일과 종료 연,월,일
     * @type {string}
     * @memberof SearchActionDto
     */
    periodEndYear?: string;
    /**
     * 종료 월
     * @type {string}
     * @memberof SearchActionDto
     */
    periodEndMonth?: string;
    /**
     * 종료 일
     * @type {string}
     * @memberof SearchActionDto
     */
    periodEndDay?: string;
    /**
     * 프로젝트ID 목록
     * @type {Array<number>}
     * @memberof SearchActionDto
     */
    projectIdList?: Array<number>;
}

/**
 * Check if a given object implements the SearchActionDto interface.
 */
export function instanceOfSearchActionDto(value: object): value is SearchActionDto {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function SearchActionDtoFromJSON(json: any): SearchActionDto {
    return SearchActionDtoFromJSONTyped(json, false);
}

export function SearchActionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchActionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'shareCode': json['shareCode'] == null ? undefined : json['shareCode'],
        'groupId': json['groupId'],
        'categoryList': json['categoryList'] == null ? undefined : json['categoryList'],
        'state_filter': json['state_filter'] == null ? undefined : json['state_filter'],
        'state': json['state'] == null ? undefined : json['state'],
        'ownerIdList': json['ownerIdList'] == null ? undefined : json['ownerIdList'],
        'tagIdList': json['tagIdList'] == null ? undefined : json['tagIdList'],
        'mediaIdList': json['mediaIdList'] == null ? undefined : json['mediaIdList'],
        'journalistIdList': json['journalistIdList'] == null ? undefined : json['journalistIdList'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'periodStartYear': json['periodStartYear'] == null ? undefined : json['periodStartYear'],
        'periodStartMonth': json['periodStartMonth'] == null ? undefined : json['periodStartMonth'],
        'periodStartDay': json['periodStartDay'] == null ? undefined : json['periodStartDay'],
        'periodEndYear': json['periodEndYear'] == null ? undefined : json['periodEndYear'],
        'periodEndMonth': json['periodEndMonth'] == null ? undefined : json['periodEndMonth'],
        'periodEndDay': json['periodEndDay'] == null ? undefined : json['periodEndDay'],
        'projectIdList': json['projectIdList'] == null ? undefined : json['projectIdList'],
    };
}

export function SearchActionDtoToJSON(value?: SearchActionDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'shareCode': value['shareCode'],
        'groupId': value['groupId'],
        'categoryList': value['categoryList'],
        'state_filter': value['state_filter'],
        'state': value['state'],
        'ownerIdList': value['ownerIdList'],
        'tagIdList': value['tagIdList'],
        'mediaIdList': value['mediaIdList'],
        'journalistIdList': value['journalistIdList'],
        'timezone': value['timezone'],
        'periodStartYear': value['periodStartYear'],
        'periodStartMonth': value['periodStartMonth'],
        'periodStartDay': value['periodStartDay'],
        'periodEndYear': value['periodEndYear'],
        'periodEndMonth': value['periodEndMonth'],
        'periodEndDay': value['periodEndDay'],
        'projectIdList': value['projectIdList'],
    };
}

