/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchFileAttachDto
 */
export interface SearchFileAttachDto {
    /**
     * 선택된 그룹 ID, 공유 대상이 이그룹인 경우에 조건으로 처리
     * @type {number}
     * @memberof SearchFileAttachDto
     */
    groupId: number;
    /**
     * 파일 유형, 공통코드 - FILE_TYPE, FILE/IMG
     * @type {string}
     * @memberof SearchFileAttachDto
     */
    fileType?: string;
}

/**
 * Check if a given object implements the SearchFileAttachDto interface.
 */
export function instanceOfSearchFileAttachDto(value: object): value is SearchFileAttachDto {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function SearchFileAttachDtoFromJSON(json: any): SearchFileAttachDto {
    return SearchFileAttachDtoFromJSONTyped(json, false);
}

export function SearchFileAttachDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchFileAttachDto {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'fileType': json['fileType'] == null ? undefined : json['fileType'],
    };
}

export function SearchFileAttachDtoToJSON(value?: SearchFileAttachDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupId': value['groupId'],
        'fileType': value['fileType'],
    };
}

