/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchNewsAlertDto
 */
export interface SearchNewsAlertDto {
    /**
     * 모니터링 이름 / 소유자 이름 검색
     * @type {string}
     * @memberof SearchNewsAlertDto
     */
    keyword?: string;
}

/**
 * Check if a given object implements the SearchNewsAlertDto interface.
 */
export function instanceOfSearchNewsAlertDto(value: object): value is SearchNewsAlertDto {
    return true;
}

export function SearchNewsAlertDtoFromJSON(json: any): SearchNewsAlertDto {
    return SearchNewsAlertDtoFromJSONTyped(json, false);
}

export function SearchNewsAlertDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchNewsAlertDto {
    if (json == null) {
        return json;
    }
    return {
        
        'keyword': json['keyword'] == null ? undefined : json['keyword'],
    };
}

export function SearchNewsAlertDtoToJSON(value?: SearchNewsAlertDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'keyword': value['keyword'],
    };
}

