/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchNewsSrchDto
 */
export interface SearchNewsSrchDto {
    /**
     * 모니터링 관리 검색 카테고리
     * @type {string}
     * @memberof SearchNewsSrchDto
     */
    category?: string;
    /**
     * 모니터링 관리 검색 Title
     * @type {string}
     * @memberof SearchNewsSrchDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchNewsSrchDto
     */
    shareCode?: string;
    /**
     * 그룹 ID
     * @type {number}
     * @memberof SearchNewsSrchDto
     */
    groupId: number;
    /**
     * 
     * @type {number}
     * @memberof SearchNewsSrchDto
     */
    ownerId?: number;
}

/**
 * Check if a given object implements the SearchNewsSrchDto interface.
 */
export function instanceOfSearchNewsSrchDto(value: object): value is SearchNewsSrchDto {
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    return true;
}

export function SearchNewsSrchDtoFromJSON(json: any): SearchNewsSrchDto {
    return SearchNewsSrchDtoFromJSONTyped(json, false);
}

export function SearchNewsSrchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchNewsSrchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'title': json['title'] == null ? undefined : json['title'],
        'shareCode': json['shareCode'] == null ? undefined : json['shareCode'],
        'groupId': json['groupId'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
    };
}

export function SearchNewsSrchDtoToJSON(value?: SearchNewsSrchDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'category': value['category'],
        'title': value['title'],
        'shareCode': value['shareCode'],
        'groupId': value['groupId'],
        'ownerId': value['ownerId'],
    };
}

