/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchNameEmailDto
 */
export interface SearchNameEmailDto {
    /**
     * 언론인명
     * @type {string}
     * @memberof SearchNameEmailDto
     */
    name: string;
    /**
     * 이메일 주소
     * @type {string}
     * @memberof SearchNameEmailDto
     */
    email: string;
}

/**
 * Check if a given object implements the SearchNameEmailDto interface.
 */
export function instanceOfSearchNameEmailDto(value: object): value is SearchNameEmailDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function SearchNameEmailDtoFromJSON(json: any): SearchNameEmailDto {
    return SearchNameEmailDtoFromJSONTyped(json, false);
}

export function SearchNameEmailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchNameEmailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
    };
}

export function SearchNameEmailDtoToJSON(value?: SearchNameEmailDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
    };
}

