/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchGroupDto
 */
export interface SearchGroupDto {
    /**
     * 그룹명 검색
     * @type {string}
     * @memberof SearchGroupDto
     */
    name?: string;
    /**
     * 인원 검색
     * @type {number}
     * @memberof SearchGroupDto
     */
    count?: number;
    /**
     * 그룹목록 IDs
     * @type {Array<number>}
     * @memberof SearchGroupDto
     */
    groupList?: Array<number>;
    /**
     * 사용자ID - 사용자가 속한 그룹찾을 때
     * @type {number}
     * @memberof SearchGroupDto
     */
    userId?: number;
    /**
     * 그룹명 ... 검색
     * @type {string}
     * @memberof SearchGroupDto
     */
    keyword?: string;
}

/**
 * Check if a given object implements the SearchGroupDto interface.
 */
export function instanceOfSearchGroupDto(value: object): value is SearchGroupDto {
    return true;
}

export function SearchGroupDtoFromJSON(json: any): SearchGroupDto {
    return SearchGroupDtoFromJSONTyped(json, false);
}

export function SearchGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'count': json['count'] == null ? undefined : json['count'],
        'groupList': json['groupList'] == null ? undefined : json['groupList'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'keyword': json['keyword'] == null ? undefined : json['keyword'],
    };
}

export function SearchGroupDtoToJSON(value?: SearchGroupDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'count': value['count'],
        'groupList': value['groupList'],
        'userId': value['userId'],
        'keyword': value['keyword'],
    };
}

