/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaggingTargetDto
 */
export interface TaggingTargetDto {
    /**
     * TargetId, NEWS or ACTTION or NW_RELEASE의 ID 
     * @type {number}
     * @memberof TaggingTargetDto
     */
    targetId: number;
    /**
     * NEWS인 경우에 뉴스 등록연월 YYYYMM 형태, NEWS인 경우 필수 
     * @type {string}
     * @memberof TaggingTargetDto
     */
    newsIndexName?: string;
}

/**
 * Check if a given object implements the TaggingTargetDto interface.
 */
export function instanceOfTaggingTargetDto(value: object): value is TaggingTargetDto {
    if (!('targetId' in value) || value['targetId'] === undefined) return false;
    return true;
}

export function TaggingTargetDtoFromJSON(json: any): TaggingTargetDto {
    return TaggingTargetDtoFromJSONTyped(json, false);
}

export function TaggingTargetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaggingTargetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'targetId': json['targetId'],
        'newsIndexName': json['newsIndexName'] == null ? undefined : json['newsIndexName'],
    };
}

export function TaggingTargetDtoToJSON(value?: TaggingTargetDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'targetId': value['targetId'],
        'newsIndexName': value['newsIndexName'],
    };
}

