/* tslint:disable */
/* eslint-disable */
/**
 * MediaBee Service API
 * MediaBee Service API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateImageFileRequest
 */
export interface UpdateImageFileRequest {
    /**
     * 
     * @type {Blob}
     * @memberof UpdateImageFileRequest
     */
    attachment: Blob;
}

/**
 * Check if a given object implements the UpdateImageFileRequest interface.
 */
export function instanceOfUpdateImageFileRequest(value: object): value is UpdateImageFileRequest {
    if (!('attachment' in value) || value['attachment'] === undefined) return false;
    return true;
}

export function UpdateImageFileRequestFromJSON(json: any): UpdateImageFileRequest {
    return UpdateImageFileRequestFromJSONTyped(json, false);
}

export function UpdateImageFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateImageFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attachment': json['attachment'],
    };
}

export function UpdateImageFileRequestToJSON(value?: UpdateImageFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'attachment': value['attachment'],
    };
}

