export const defaultFilter = {
  and: '',
  or: '',
  not: '',
  period: { id: '', name: '선택' },
  startPeriod: new Date(),
  endPeriod: new Date(),
  periodTag: [],
  mediaType: [],
  mediaValue: { id: '', name: '선택' },
  mediaTagList: [],
  journalistTagList: [],
  tone: [],
  tag: [],
  url: '',
  publishingPeriod: [],
  mediaBookList: [],
  clipbookValue: [],
  clipbook: { id: '', name: '선택' },
  coverage: { id: '', name: '선택' },
  informationType: { id: 'USERADD', name: '개인 추가 뉴스' },
  news_id: 0,
}
