import tempImg from '/public/assets/png/temp.jpg'
import icoSvgData from '~/components/common/ui/icon/icoSvgData.json'
import type { PeopleListItem } from '~/types/contents/Common'

export const mbPeopleListData: PeopleListItem[] = [
  {
    id: '1',
    name: '서정민',
    nameLink: 'https://www.naver.com',
    isAddedPersonally: false,
    imageSrc: '',
    mediaValue: 62510,
    location: '서울 중구',
    media: '중앙일보',
    hasMediaLink: true,
    department: '',
    position: '문화부 기자',
    partTags: ['IT/전자', '소프트웨어', '인터넷'],
  },
  {
    id: '2',
    name: '서정민',
    nameLink: 'https://www.naver.com',
    isAddedPersonally: true,
    imageSrc: '',
    mediaValue: 62510,
    location: '서울 중구',
    media: '중앙일보',
    hasMediaLink: true,
    department: '',
    position: '문화부 기자',
    partTags: ['IT/전자', '소프트웨어', '인터넷'],
  },
  {
    id: '3',
    name: '서정민',
    nameLink: 'https://www.naver.com',
    isAddedPersonally: false,
    imageSrc: tempImg,
    mediaValue: 62510,
    location: '서울 중구',
    media: '중앙일보',
    hasMediaLink: true,
    department: '',
    position: '문화부 기자',
    partTags: ['IT/전자', '소프트웨어', '인터넷'],
  },
  {
    id: '4',
    name: '서정민',
    nameLink: 'https://www.naver.com',
    isAddedPersonally: false,
    imageSrc: '',
    mediaValue: 62510,
    location: '서울 중구',
    media: '중앙일보',
    hasMediaLink: true,
    department: '',
    position: '문화부 기자',
    partTags: ['IT/전자', '소프트웨어', '인터넷'],
    relatedNews: [
      {
        title: 'LG생활건강, ‘CNP Rx 스킨 레쥬버네이팅 미라클 앰플 인 쿠션’ 출시',
        status: '보도자료 초안',
        author: '홍길동',
        date: '06-24',
        year: '2022',
        icon: icoSvgData.fileEarmarkText,
      },
      {
        title: '메가존, 클라우드 MSP사업자로 성장…원스탑 토탈 서비스 제공',
        status: '클립북',
        author: '홍길동',
        date: '05-18',
        year: '2022',
        icon: icoSvgData.envelope,
      },
      {
        title: '중앙일보 서정민 전화 통화',
        status: '전화 완료',
        author: '홍길동',
        date: '04-27',
        year: '2021',
        icon: icoSvgData.pencil,
      },
    ],
  },
  {
    id: '5',
    name: '장지승',
    nameLink: 'https://www.naver.com',
    isAddedPersonally: false,
    imageSrc: '',
    mediaValue: 62510,
    location: '서울 중구',
    media: '중앙일보',
    hasMediaLink: true,
    department: '',
    position: '문화부 기자',
    partTags: ['IT/전자', '소프트웨어', '인터넷'],
    relatedNews: [
      {
        title: 'LG생활건강, ‘CNP Rx 스킨 레쥬버네이팅 미라클 앰플 인 쿠션’ 출시',
        status: '보도자료 초안',
        author: '홍길동',
        date: '06-24',
        year: '2022',
        icon: icoSvgData.fileEarmarkText,
      },
      {
        title: '메가존, 클라우드 MSP사업자로 성장…원스탑 토탈 서비스 제공',
        status: '클립북',
        author: '홍길동',
        date: '05-18',
        year: '2022',
        icon: icoSvgData.envelope,
      },
      {
        title: '중앙일보 서정민 전화 통화',
        status: '전화 완료',
        author: '홍길동',
        date: '04-27',
        year: '2021',
        icon: icoSvgData.pencil,
      },
      {
        title: 'LG생활건강, ‘CNP Rx 스킨 레쥬버네이팅 미라클 앰플 인 쿠션’ 출시',
        status: '보도자료 초안',
        author: '홍길동',
        date: '06-24',
        year: '2022',
        icon: icoSvgData.fileEarmarkText,
      },
      {
        title: '메가존, 클라우드 MSP사업자로 성장…원스탑 토탈 서비스 제공',
        status: '클립북',
        author: '홍길동',
        date: '05-18',
        year: '2022',
        icon: icoSvgData.envelope,
      },
      {
        title: '중앙일보 서정민 전화 통화',
        status: '전화 완료',
        author: '홍길동',
        date: '04-27',
        year: '2021',
        icon: icoSvgData.pencil,
      },
      {
        title: 'LG생활건강, ‘CNP Rx 스킨 레쥬버네이팅 미라클 앰플 인 쿠션’ 출시',
        status: '보도자료 초안',
        author: '홍길동',
        date: '06-24',
        year: '2022',
        icon: icoSvgData.fileEarmarkText,
      },
      {
        title: '메가존, 클라우드 MSP사업자로 성장…원스탑 토탈 서비스 제공',
        status: '클립북',
        author: '홍길동',
        date: '05-18',
        year: '2022',
        icon: icoSvgData.envelope,
      },
      {
        title: '중앙일보 서정민 전화 통화',
        status: '전화 완료',
        author: '홍길동',
        date: '04-27',
        year: '2021',
        icon: icoSvgData.pencil,
      },
      {
        title: 'LG생활건강, ‘CNP Rx 스킨 레쥬버네이팅 미라클 앰플 인 쿠션’ 출시',
        status: '보도자료 초안',
        author: '홍길동',
        date: '06-24',
        year: '2022',
        icon: icoSvgData.fileEarmarkText,
      },
      {
        title: '메가존, 클라우드 MSP사업자로 성장…원스탑 토탈 서비스 제공',
        status: '클립북',
        author: '홍길동',
        date: '05-18',
        year: '2022',
        icon: icoSvgData.envelope,
      },
      {
        title: '중앙일보 서정민 전화 통화',
        status: '전화 완료',
        author: '홍길동',
        date: '04-27',
        year: '2021',
        icon: icoSvgData.pencil,
      },
    ],
  },
]
